from enum import StrEnum, Enum, IntEnum, FloatEnum

import pycountry


class DimensionLengthUnits(StrEnum):

    MILES = "mi"
    FEET = "ft"
    INCH = "in"
    MCM = "MCM"  # Thousand Circular Mil
    AWG = "AWG"  # American Wire Gauge
    MILS = "mils"  # Thousandths of an inch
    KMILS = "kmils"  # Kilo Mils (thousands of mils)
    
class ElectricalUnits(StrEnum):
    A = "A" # Amperes
    V = "V" # Voltage
    KV = "KV"  # Kilovolts
    W = "W"  # Watts
    KW = "KW"  # Kilowatts
    MW = "MW"  # Megawatts
    HZ = "Hz"  # Hertz
    VA = "VA"  # Volt-Amperes
    KVA = "KVA"  # Kilovolt-Amperes

class PoleClass(StrEnum):
    CLASS_1 = "Class 1"
    CLASS_2 = "Class 2"
    CLASS_3 = "Class 3"
    CLASS_4 = "Class 4"
    CLASS_5 = "Class 5"
    CLASS_6 = "Class 6"
    
class PoleConstructionMaterical(StrEnum):
    WOOD = "wood"
    FIBER_GLASS = "fiber_glass"

class CrossarmConstructionMaterial(StrEnum):
    WOOD = "wood"
    STEEL = "steel"
    FIBER_GLASS = "fiber_glass"

class ConductorConstructionMaterial(StrEnum):
    COPPER = "copper"
    CU = "cu"
    ALUMINIUM = "aluminium"
    AL = "al"
    ACSR = "ACSR"
    AAC = "AAC"
    AAAC = "AAAC"
    AACSR = "AACSR"
    TACSR = "TACSR"
    TACSR_AW = "TACSR/AW"

class ConductorConstructionType(StrEnum):
    STRANDED = "stranded"
    SOLID = "solid"

class CableInstallationMethod(StrEnum):
    DIRECT_BURIED = "direct_buried"
    UNDERGROUND_DUCT = "underground_duct"
    OVERHEAD = "overhead" 

class PolymericMaterial(StrEnum):
    XLPE = "xlpe"
    EPR = "epr"
    SEMI_CONDUCTING_XLPE = "semi_conducting_xlpe"
    SEMI_CONDUCTING_EPR = "semi_conducting_epr"
    PVC = "pvc"
    PE = "pe"
    NYLON = "nylon"
    RUBBER = "rubber"

class NeutralOrShieldMaterial(str, Enum):
    ANNEALED_COPPER = "annealed_copper"
    TINNED_COPPER = "tinned_copper"
    ALUMINUM = "aluminum"

class NeutralConfiguration(StrEnum):
    CONCENTRIC = "concentric"
    TAPE = "tape" 
    FLAT = "flat" # flat strip

class NeutralType(StrEnum):
    FULL = "full"
    ONE_THIRD = "one_third"  

class ConduitConstructionMaterial(StrEnum):
    STEEL = "steel"
    GALVANIZED_STEEL = "galvanized_steel"
    STAINLESS_STEEL = "stainless_steel"
    ALUMINUM = "aluminum"
    PVC = "PVC"  
    HDPE = "HDPE"  # High-Density Polyethylene
    FIBERGLASS = "fiberglass"

class ConduitType(StrEnum):
    RMC = "RMC"  # Rigid Metal Conduit
    IMC = "IMC"  # Intermediate Metal Conduit
    EMT = "EMT"  # Electrical Metallic Tubing
    RNC = "RNC"  # Rigid Non-Metallic Conduit (e.g., PVC)
    HDPE = "HDPE"  # High-Density Polyethylene Conduit
    FMC = "FMC"  # Flexible Metal Conduit
    LFMC = "LFMC"  # Liquid-Tight Flexible Metal Conduit
    LFNC = "LFNC"  # Liquid-Tight Flexible Non-Metallic Conduit
    FRC = "FRC"  # Fiberglass Reinforced Conduit
    SPLIT_DUCT = "SPLIT_DUCT"  # Split PVC or HDPE Conduit
    DIRECT_BURIAL = "DIRECT_BURIAL"  # Direct Burial Conduit (e.g., HDPE or PVC without additional protection)

class ConduitStandardTradeSize(FloatEnum):
    # in inches
    HALF = 0.5
    THREE_QUARTER = 0.75
    ONE = 1.0
    ONE_AND_ONE_QUARTER = 1.25
    ONE_AND_ONE_HALF = 1.5
    TWO = 2.0
    TWO_AND_ONE_HALF = 2.5
    THREE = 3.0
    THREE_AND_ONE_HALF = 3.5
    FOUR = 4.0
    FIVE = 5.0
    SIX = 6.0

class ConduitStandardMetricSize(IntEnum):
    #in mm
    _16 = 16
    _21 = 21
    _27 = 27
    _35 = 35
    _41 = 41
    _53 = 53
    _63 = 63
    _78 = 78
    _91 = 91
    _103 = 103
    _129 = 129
    _155 = 155

class NEMARating(StrEnum):
    NEMA_1 = "NEMA 1" # Indoor commercial/utility
    NEMA_3R = "NEMA 3R" # Outdoor, rainproof
    NEMA_4 = "NEMA 4" # Outdoor, water-tight
    NEMA_4X = "NEMA 4X" # Corrosive outdoor 
    NEMA_12 = "NEMA 12" # Indoor, dust/oil/moisture-tight

class DHClass(StrEnum):
    DH_1 = "DH-1"  
    DH_2 = "DH-2"  
    DH_3 = "DH-3"  
    DH_4 = "DH-4"  
    DH_5 = "DH-5"  

class TransformerCoolingMethods(StrEnum):
    ONAN = "ONAN"  # Oil Natural Air Natural
    ONAF = "ONAF"  # Oil Natural Air Forced
    OFAF = "OFAF"  # Oil Forced Air Forced
    OFWF = "OFWF"  # Oil Forced Water Forced
    AN = "AN"  # Air Natural
    AF = "AF"  # Air Forced

class TransformerInsulationTempClass(StrEnum):
    A = "A"  # 105°C
    B = "B"  # 130°C
    F = "F"  # 155°C
    H = "H"  # 180°C
    C = "C"  # 200°C
    Custom = "Custom"  # Custom temperature class

class TrippingCurves(StrEnum):
    CURVE_B = "Curve B"
    CURVE_C = "Curve C"
    CURVE_D = "Curve D"
    CURVE_E = "Curve E"
    CURVE_K = "Curve K"
    CURVE_Z = "Curve Z"

class CircuitBreakerTypes(StrEnum):
    MCB = "MCB"  # Miniature Circuit Breaker
    MCCB = "MCCB"  # Molded Case Circuit Breaker
    RCCB_RCD = "RCCB/RCD"  # Residual Current Circuit Breaker / Residual Current Device
    ELCB = "ELCB"  # Earth Leakage Circuit Breaker
    RCBO = "RCBO"  # Residual Current Circuit Breaker with Overcurrent Protection
    AFCI = "AFCI"  # Arc Fault Circuit Interrupter
    GFCI = "GFCI"  # Ground Fault Circuit Interrupter
    DC_CB = "DC_CB"  # DC Circuit Breaker
    WIFI_CB = "WIFI_CB"  # Wi-Fi enabled Circuit Breaker
    ACB = "ACB"  # Air Circuit Breaker
    VCB = "VCB"  # Vacuum Circuit Breaker
    MPCB = "MPCB"  # Motor Protection Circuit Breaker
    SF6_CB = "SF6_CB"  # SF6 Circuit Breaker
    MOCB = "MOCB"  # Oil Circuit Breaker
    BOCB = "BOCB"  # Bushing Oil Circuit Breaker
    AUTOMOTIVE_CB = "AUTOMOTIVE_CB"  # Automotive Circuit Breaker
    HVDC_CB = "HVDC_CB"  # HVDC Circuit Breaker
    CAFCI = "CAFCI"  # Combination Arc Fault Circuit Interrupter (arc and ground fault protection)

class CircuitBreakerOperatingMechanism(StrEnum):
    SPRING_OPERATED = "Spring Operated"
    HYDRAULIC = "Hydraulic"
    ELECTROMAGNETIC = "Electromagnetic"
    MAGNETIC_HYDRAULIC = "Magnetic Hydraulic"
    PNEUMATIC = "Pneumatic"

class CircuitBreakerMountingType(StrEnum):
    DRAW_OUT = "Draw Out" # Withdrawable (slides in/out mechanical guides)
    PLUG_IN = "Plug-In" # Removable (plugs into a base)
    BOLT_ON = "Bolt-On" # Fixed
    DIN_RAIL = "DIN Rail" # Slap-on
    ENCLOSED_RACK = "Enclosed Rack" # Mounted within complete enclosure or rack

class RelayTypes(StrEnum):
    OVERCURRENT = "Overcurrent"
    DISTANCE = "Distance"
    DIFFERENTIAL = "Differential"
    REFLEX = "Reflex"
    DIRECTIONAL = "Directional"
    UNDER_VOLTAGE = "Under Voltage"
    OVER_VOLTAGE = "Over Voltage"
    FREQUENCY = "Frequency"
    TEMPERATURE = "Temperature"
    PHASE_ANGLE = "Phase Angle"
    GROUND_FAULT = "Ground Fault"
    VOLTAGE_RELAY = "Voltage Relay"
    CURRENT_RELAY = "Current Relay"
    TIME_DELAY = "Time Delay"
    PROTECTIVE_RELAY = "Protective Relay"
    NUMERIC_RELAY = "Numeric Relay"
    MICROPROCESSOR_BASED = "Microprocessor-Based Relay"
    SOLID_STATE = "Solid State Relay"
    ELECTROMECHANICAL = "Electromechanical Relay"

class RelayCommunicationProtocols(StrEnum):
    MODBUS = "Modbus"
    DNP3 = "DNP3"
    IEC_61850 = "IEC 61850"
    PROPRIETARY = "Proprietary"
    OTHER = "Other"

class MountingTypesMV(StrEnum):
    POLE = "Pole-Mounted"
    PAD = "Pad-Mounted"
    WALL = "Wall-Mounted"
    INDOOR = "Indoor"
    UNDERGROUND = "Underground"

class MountingTypesLV(StrEnum):
    CONDUIT = "Conduit-Mounted"
    PANEL = "Panel-Mounted"
    SURFACE = "Surface-Mounted"
    WALL = "Wall-Mounted"
    DIN = "DIN Rail"
    INDOOR = "Indoor"

class MountingTypesFuses(StrEnum):
    POLE = "Pole-Mounted" # MV cutouts, expulsion fuses on distribution poles
    PANEL = "Panel-Mounted" # LV cartridge fuses in control panels or switchboards
    SWITCHGEAR = "Switchgear-Mounted" # Ampgard or other cubicles for MV fuses
    DIN = "DIN Rail" # smaller cartridge fuses for LV protection
    INDOOR = "Indoor"

class FuseTypes(StrEnum):
    INLINE = "Inline"
    EXPULSION = "Expulsion"
    CUTOUT = "Cutout"
    CARTRIDGE = "Cartridge"

class MountingTypesRelays(StrEnum):
    PANEL = "Panel-Mounted"
    DIN = "DIN Rail"
    SURFACE = "Surface-Mounted"
    WALL = "Wall-Mounted"
    INDOOR = "Indoor"

class RecloserControlTypes(StrEnum):
    HYDRAULIC = "Hydraulic"
    ELECTRONIC = "Electronic"
    MICROPROCESSOR = "Microprocessor"

class RecloserOperatingDutyCycles(StrEnum):
    NORMAL = "Normal"
    HEAVY = "Heavy"
    EXTRA_HEAVY = "Extra Heavy"

class InsulationMedium(StrEnum):
    AIR = "Air"
    VACUUM = "Vacuum"
    SF6 = "SF6"

class HousingMaterial(StrEnum):
    POLYMERIC = "Polymeric"
    PORCELAIN = "Porcelain"
    GLASS = "Glass"

class LocationType(StrEnum):
    INDOOR = "Indoor"
    OUTDOOR = "Outdoor"

class FuseTimeCurrentCharacteristic(StrEnum):
    FAST_ACTING = "Fast Acting"
    TIME_DELAY = "Time Delay"
    VERY_FAST_ACTING = "Very Fast Acting"
    ULTRA_FAST_ACTING = "Ultra Fast Acting"

class FuseClasses(StrEnum):
    CLASS_CC = "Class CC"   # (midget)
    CLASS_J = "Class J"
    CLASS_H = "Class H"
    CLASS_K5 = "Class K5"
    CLASS_L = "Class L"
    CLASS_T = "Class T"
    RK1 = "RK1"         # R subclass, offers advanced current limitations and short-circuit protection
    RK5 = "RK5"         # R subclass, less limiting than RK1

class UnitCostCategory(StrEnum):
    CATEGORY_1 = "12/16kV 480 volt transformer - includes 100' Sec. cable length"
    CATEGORY_2 = "Overhead to Underground (UG)- Set Pole and make up Cable"
    CATEGORY_3 = "Overhead (OH) Service"
    CATEGORY_4 = "Underground to Underground - Cable with Terminators"
    CATEGORY_5 = "Metering"
    CATEGORY_6 = "Telemetry"
    CATEGORY_7 = "System Equipment"

class SourceName(StrEnum):
    STATE_ELECTRIC_SUPPLY_CO= "StatElectricSupplyCo"
    CRAWFORD_ELECTRIC_SUPPLY = "CrawfordElectricSupply"
    CAPITAL_ELECTRIC_SUPPLY = "CapitalElectricSupply"
    WIRE_AND_CABLE_YOUR_WAY = "WireAndCableYourWay"
    LED_LIGHTING_SUPPLY = "LedLightingSupply"
    FAR_WEST_CORROSION = "FarWestCorrosion"
    PRO_WIRE_AND_CABLE = "ProWireAndCable"
    ONE_SOURCE_DIST = "OneSourceDist"
    LINEMAN_TOOLS = "LinemanTools"
    CLOSE_LUBMER = "CloseLumber"
    SOUTH_WIRE = "SouthWire"
    BAY_POWER = "BayPower"
    ALIBABA = "Alibaba"
    COILUS = "Coilus"
    SHIPPO = "Shippo"
    PLATT = "Platt"
    PEPCO = "Pepco"

class PricingInfoType(StrEnum):
    ACTUAL_COMPONENT_COST = "ACTUAL_COMPONENT_COST"
    AGGREGATED_UNIT_COST = "AGGREGATED_UNIT_COST"
    ESTIMATED_COMPONENT_COST = "ESTIMATED_COMPONENT_COST"

class DataSource(StrEnum):
    UTILITY = "UTILITY"
    VENDOR = "VENDOR"
    RETAILER = "RETAILER"
    PUC = "PUC"
    RESEARCH_ORGANIZATION = "RESEARCH_ORGANIZATION"

class DataSourceType(StrEnum):
    
    WEBSITE = "WEBSITE"
    PDF = "PDF"
    API = "API"

class UtilityType(StrEnum):
    
    INVESTOR_OWNED = "INVESTOR_OWNED"
    MANICUPALITY = "MANICUPALITY"
    COOPERATIVE = "COOPERATIVE"


Country = StrEnum("Country", {country.alpha_2: country.name  for country in pycountry.countries})


# class Country(StrEnum):
#     @staticmethod
#     def list():
#         return {country.alpha_2: country.name for country in pycountry.countries}

class OperatingFrequency(IntEnum):
    HERTZ_50 = 50
    HERTZ_60 = 60

class VoltageClass(IntEnum):
    KV_5 = 5
    KV_15 = 15
    KV_25 = 25
    KV_35 = 35
 
class EquipmentType(StrEnum):
    CONDUCTOR = "CONDUCTOR"
    CABLE = "cable"
    ELBOWS = "ELBOWS"
    DISTRIBUTION_TRANSFORMER = "DISTRIBUTION_TRANSFORMER"
    CONDUIT = "conduit"
    POWER_TRANSFORMER = "POWER_TRANSFORMER"
    VOLTAGE_REGULATOR = "VOLTAGE_REGULATOR"
    CAPACITOR_BANK = "CAPACITOR_BANK"
    REACTOR = "REACTOR"
    RECLOSER = "RECLOSER"
    LOAD_TAP_CHANGER = "LOAD_TAP_CHANGER"
    SURGE_ARRESTER = "SURGE_ARRESTER"
    FUSE = "FUSE"
    RELAY = "RELAY"
    REMOTE_TERMINAL_UNIT = "REMOTE_TERMINAL_UNIT"
    METER = "METER"
    CUSTOMER_LOAD_PANEL = "CUSTOMER_LOAD_PANEL"
    POTENTIAL_TRANSFORMER = "POTENTIAL_TRANSFORMER"
    CURRENT_TRANSFORMER = "CURRENT_TRANSFORMER"
    VAULTS = "VAULTS"
    INSULATOR = "INSULATOR"
    CROSS_ARM = "crossarm"
    POLE = "pole"
    
    SWITCHGEAR = "SWITCHGEAR"
    LIMIT_SWITCH = "limit_switch"
    DISCONNECT_SWITCH = "disconnect_switch"
    TIE_LINE_SWITCH = "TIE_LINE_SWITCH"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    SENSOR = "sensor"
    FUSE_CUTOUT = "fuse_cutout"

    HOUSE_PANEL = "house_panel"
    
    GROUNDING_ROD = "grounding_rod"

    # Low cost impact (likely)
    ANCHOR = "ANCHOR"
    GUY_WIRE = "GUY_WIRE"
    CABLE_SPLICER = "CABLE_SPLICER"
    HANDHOLES = "HANDHOLES"
    FAULT_INDICATOR = "FAULT_INDICATOR"
    JUNCTION_BOXES = "JUNCTION_BOXES"
    MANHOLE_COVER = "MANHOLE_COVER"
    COMBINER_BOX = "combiner_box"
    METER_CENTER = "meter_center"

    # Captured in ATB (?)
    BATTERY= "BATTERY"
    BATTERY_CONTROLLER = "battery_controller"
    PV_PANEL = "pv_panel"
    POWER_OPTIMIZER = "power_optimizer"
    INVERTER = "INVERTER"
    GENERATOR = "generator"

    # Contact EV group
    EV_CHARGER = "ev_charger"

  

class Utility(StrEnum):

    ALABAMA_MUNICIPAL_ELECTRIC_AUTHORITY = "Alabama Municipal Electric Authority"
    ALBERTVILLE_MUNICIPAL_UTILITIES_BOARD = "Albertville Municipal Utilities Board"
    ARAB_ELECTRIC_COOPERATIVE = "Arab Electric Cooperative, Inc."
    ALABAMA_POWER = "Alabama Power"
    ATHENS_UTILITIES = "Athens Utilities"
    CHEROKEE_ELECTRIC_COOPERATIVE = "Cherokee Electric Cooperative"
    CULLMAN_ELECTRIC_COOPERATIVE = "Cullman Electric Cooperative"
    UTILITIES_BOARD_CULLMAN = "Utilities Board of the City of Cullman"
    DECATUR_UTILITIES = "Decatur Utilities"
    FLORENCE_UTILITIES = "Florence Utilities"
    FRANKLIN_ELECTRIC_COOPERATIVES = "Franklin Electric Cooperatives"
    GUNTERSVILLE_ELECTRIC_BOARD = "Guntersville Electric Board"
    HUNTSVILLE_UTILITIES = "Huntsville Utilities"
    JOE_WHEELER_ELECTRIC_MEMBER_COOPERATIVE = "Joe Wheeler Electric Member Cooperative"
    MARSHALL_DEKALB_ELECTRIC_COOPERATIVE = "Marshall-DeKalb Electric Cooperative"
    POWERSOUTH_ENERGY_COOPERATIVE = "PowerSouth Energy Cooperative"
    SAND_MOUNTAIN_ELECTRIC_COOPERATIVE = "Sand Mountain Electric Cooperative"
    SCOTTSBORO_ELECTRIC_POWER_BOARD = "Scottsboro Electric Power Board"
    TOMBIGBEE_ELECTRIC_COOPERATIVE = "Tombigbee Electric Cooperative"
    WIREGRASS_ELECTRIC_COOPERATIVE = "Wiregrass Electric Cooperative"
    ALASKA_ELECTRIC_LIGHT_POWER = "Alaska Electric Light & Power"
    CHUGACH_ELECTRIC_ASSOCIATION = "Chugach Electric Association"
    COPPER_VALLEY_ELECTRIC_ASSOCIATION = "Copper Valley Electric Association"
    GOLDEN_VALLEY_ELECTRIC_ASSOCIATION = "Golden Valley Electric Association"
    KODIAK_ELECTRIC_ASSOCIATION = "Kodiak Electric Association"
    ARIZONA_PUBLIC_SERVICE = "Arizona Public Service"
    SALT_RIVER_PROJECT = "Salt River Project"
    TUCSON_ELECTRIC_POWER = "Tucson Electric Power"
    UNISOURCE_ENERGY_SERVICES = "UniSource Energy Services"
    PAGE_POWER_AND_WATER = "Page Power and Water"
    SOUTHWESTERN_ELECTRIC_POWER_COMPANY = "Southwestern Electric Power Company"
    ENTERGY_ARKANSAS = "Entergy Arkansas, Inc."
    ASSOCIATED_ELECTRICAL_COOP = "Associated Electrical Cooperative Incorporated"
    ALAMEDA_MUNICIPAL_POWER = "Alameda Municipal Power"
    ANAHEIM_PUBLIC_UTILITIES = "Anaheim Public Utilities"
    AZUSA_LIGHT_WATER = "Azusa Light & Water"
    BURBANK_WATER_POWER = "Burbank Water & Power"
    EAST_BAY_MUNICIPAL_UTILITY_DISTRICT = "East Bay Municipal Utility District"
    GLENDALE_PUBLIC_SERVICE = "Glendale Public Service Department"
    GRIDLEY_MUNICIPAL_UTILITIES = "Gridley Municipal Utilities"
    HEALDSBURG_MUNICIPAL_ELECTRIC = "Healdsburg Municipal Electric Department"
    IMPERIAL_IRRIGATION_DISTRICT = "Imperial Irrigation District"
    ISLAND_ENERGY = "Island Energy"
    MODESTO_IRRIGATION_DISTRICT = "Modesto Irrigation District"
    LOS_ANGELES_DWP = "Los Angeles Department of Water and Power"
    NEVADA_IRRIGATION_DISTRICT = "Nevada Irrigation District"
    OBRIEN_COGENERATION = "O'Brien Cogeneration"
    ORANGE_COUNTY_POWER_AUTHORITY = "Orange County Power Authority"
    PACIFIC_GAS_ELECTRIC = "Pacific Gas and Electric"
    PASADENA_WATER_POWER = "Pasadena Water & Power"
    PACIFICORP_PACIFIC_POWER = "PacifiCorp (Pacific Power)"
    RIVERSIDE_PUBLIC_UTILITIES = "Riverside Public Utilities"
    SACRAMENTO_MUNICIPAL_UTILITY_DISTRICT = "Sacramento Municipal Utility District"
    SAN_DIEGO_GAS_ELECTRIC = "San Diego Gas & Electric"
    SAN_FRANCISCO_PUBLIC_UTILITIES = "San Francisco Public Utilities Commission"
    SILICON_VALLEY_POWER = "Silicon Valley Power"
    SIERRA_PACIFIC_POWER = "Sierra-Pacific Power"
    SOUTHERN_CALIFORNIA_EDISON = "Southern California Edison"
    SOUTHERN_CALIFORNIA_PUBLIC_POWER_AUTHORITY = "Southern California Public Power Authority"
    TID_TURLOCK_IRRIGATION_DISTRICT = "TID Water & Power - Turlock Irrigation District"
    INTERMOUNTAIN_RURAL_ELECTRICAL_ASSOCIATION = "Intermountain Rural Electrical Association"
    COLORADO_SPRINGS_UTILITIES = "Colorado Springs Utilities"
    PLATTE_RIVER_POWER_AUTHORITY = "Platte River Power Authority"
    UNITED_POWER_INC = "United Power, Inc."
    TRI_STATE_GENERATION_TRANSMISSION = "Tri-State Generation and Transmission Association"
    POUDRE_VALLEY_RURAL_ELECTRIC = "Poudre Valley Rural Electric Association"
    LA_PLATA_ELECTRIC_ASSOCIATION = "La Plata Electric Association"
    WESTERN_AREA_POWER_ADMINISTRATION = "Western Area Power Administration"
    CITY_OF_FOUNTAIN_ELECTRIC = "City of Fountain Electric"
    AVANGRID = "AVANGRID (The United Illuminating Company)"
    EVERSOURCE_ENERGY = "Eversource Energy (Connecticut Light and Power, Northeast Utilities)"
    CONNECTICUT_LIGHT_POWER = "Connecticut Light & Power"
    UNITED_ILLUMINATING = "United Illuminating Co."
    SOUTH_NORWALK_ELECTRIC = "South Norwalk Electric and Water"
    NORTHEAST_UTILITIES = "Northeast Utilities"
    WALLINGFORD_ELECTRIC = "Wallingford Electric Department"
    POSITIVE_ENERGY = "Positive Energy Electricity Supply LLC"
    VIRIDIAN_ENERGY = "Viridian Energy"
    BOZRAH_LIGHT_POWER = "Bozrah Light & Power"
    YOUR_ENERGY_CO = "Your Energy Co"
    UI_CO = "UI Co."
    CT_GREEN_ENERGY = "CT Green Energy by Viridian"
    PUBLIC_POWER = "Public Power, LLC"
    NORWICH_PUBLIC_UTILITIES = "Norwich Public Utilities"
    CITY_DOVER_ELECTRIC = "City of Dover Electric Department"
    CITY_MILFORD_ELECTRIC = "City of Milford Electric Department"
    CITY_NEWARK_ELECTRIC = "City of Newark Electric Department"
    WAPDA = "WAPDA"
    CITY_SEAFORD_ELECTRIC = "City of Seaford Electric Department"
    DELAWARE_ELECTRIC_COOP = "Delaware Electric Cooperative"
    DELAWARE_MUNICIPAL_ELECTRIC = "Delaware Municipal Electric Corporation"
    DELMARVA_POWER = "Delmarva Power, a subsidiary of Exelon"
    LEWES_BOARD = "Lewes Board of Public Works"
    MUNICIPAL_SERVICES_COMMISSION = "Municipal Services Commission of the City of New Castle"
    TOWN_CLAYTON_ELECTRIC = "Town of Clayton Electric Department"
    TOWN_MIDDLETOWN_ELECTRIC = "Town of Middletown Electric Department"
    TOWN_SMRYNA_ELECTRIC = "Town of Smyrna Electric Department"
    PEPCO = "PEPCO, a subsidiary of Exelon"
    BEACHES_ENERGY_SERVICES = "Beaches Energy Services"
    CENTRAL_FLORIDA_ELECTRIC = "Central Florida Electric Cooperative"
    CHOCTAWHATCHEE_ELECTRIC = "Choctawhatchee Electric Cooperative"
    CITY_ALACHUA_PUBLIC = "City of Alachua Public Services Department"
    CITY_BARTOW_ELECTRIC = "City of Bartow Electric Department"
    CITY_BLOUNTSTOWN_ELECTRIC = "City of Blountstown Electric Department"
    CITY_BUSHNELL_UTILITIES = "City of Bushnell Utilities Department"
    CITY_CHATTAHOOCHEE_ELECTRIC = "City of Chattahoochee Electric Department"
    CITY_FORT_MEADE_UTILITIES = "City of Fort Meade Utilities Department"
    CITY_GREEN_COVE_SPRINGS = "City of Green Cove Springs Utilities Department"
    CITY_LAKE_WORTH_UTILITIES = "City of Lake Worth Utilities Department"
    CITY_MOORE_HAVEN_UTILITIES = "City of Moore Haven Utilities Department"
    CITY_MOUNT_DORA_ELECTRIC = "City of Mount Dora Electric Utility"
    CITY_NEW_SMRYNA_BEACH = "City of New Smyrna Beach Utilities Commission"
    CITY_NEWBERRY_ELECTRIC = "City of Newberry Electric Utility"
    CITY_QUINCY_UTILITIES = "City of Quincy Utilities Department"
    CITY_STARKE_UTILITIES = "City of Starke Utilities Department"
    CITY_TALLAHASSEE_UTILITIES = "City of Tallahassee Utilities"
    CITY_VERO_BEACH_ELECTRIC = "City of Vero Beach Electric Utilities"
    CITY_WACHULA_UTILITIES = "City of Wachula Utilities"
    CITY_WILLISTON_UTILITIES = "City of Williston Utilities Department"
    CITY_WINTER_PARK_ELECTRIC = "City of Winter Park Electric Utility Department"
    CLAY_ELECTRIC_COOP = "Clay Electric Cooperative"
    CLEWISTON_UTILITIES = "Clewiston Utilities"
    DUKE_ENERGY_FLORIDA = "Duke Energy Florida, a part of Duke Energy"
    ESCAMBIA_RIVER_ELECTRIC = "Escambia River Electric Cooperative"
    FLORIDA_KEYS_ELECTRIC = "Florida Keys Electric Cooperative"
    FLORIDA_MUNICIPAL_POWER = "Florida Municipal Power Agency"
    FLORIDA_POWER_LIGHT = "Florida Power & Light, a part of NextEra Energy"
    FLORIDA_PUBLIC_UTILITIES = "Florida Public Utilities, a part of Chesapeake Utilities"
    FORT_PIERCE_UTILITIES = "Fort Pierce Utilities Authority"
    GAINESVILLE_UTILITIES = "Gainesville Regional Utilities"
    GLADES_ELECTRIC_COOP = "Glades Electric Cooperative"
    GULF_COAST_ELECTRIC = "Gulf Coast Electric Cooperative"
    GULF_POWER_COMPANY = "Gulf Power Company, a part of NextEra Energy"
    HOMESTEAD_PUBLIC_SERVICES = "Homestead Public Services"
    JEA = "JEA"
    KEYS_ENERGY_SERVICES = "Keys Energy Services"
    KISSIMMEE_UTILITY = "Kissimmee Utility Authority"
    LAKELAND_ELECTRIC = "Lakeland Electric"
    LEE_COUNTY_ELECTRIC = "Lee County Electric Cooperative"
    LEESBURG_ELECTRIC = "Leesburg Electric Department"
    OCALA_ELECTRIC = "Ocala Electric Utility"
    OKEFENOKE_RURAL_ELECTRIC = "Okefenoke Rural Electric Membership Corporation"
    ORLANDO_UTILITIES = "Orlando Utilities Commission"
    PALM_PEACH = "Palm Peach"
    PEACE_RIVER_ELECTRIC = "Peace River Electric Cooperative"
    PROGRESS_ENERGY_FLORIDA = "Progress Energy Florida"
    POWERSOUTH_ENERGY = "PowerSouth Energy Cooperative"
    REEDY_CREEK_ENERGY = "Reedy Creek Energy Services"
    ST_CLOUD_UTILITIES = "St. Cloud Utilities"
    SEMINOLE_ELECTRIC = "Seminole Electric Cooperative"
    SUMTER_ELECTRIC = "Sumter Electric Cooperative"
    SUWANNEE_VALLEY_ELECTRIC = "Suwannee Valley Electric Cooperative"
    TALQUIN_ELECTRIC = "Talquin Electric Cooperative"
    TECO_ENERGY = "TECO Energy, a part of Emera"
    TOWN_HAVANA_UTILITIES = "Town of Havana Utilities"
    TRI_COUNTY_ELECTRIC = "Tri-County Electric Cooperative"
    WEST_FLORIDA_ELECTRIC = "West Florida Electric Cooperative"
    WITHLACOOCHEE_RIVER_ELECTRIC = "Withlacoochee River Electric Cooperative"
    GEORGIA_POWER = "Georgia Power, a part of the Southern Company"
    MEAG_POWER = "Municipal Electric Authority of Georgia (MEAG Power)"
    OGLETHORPE_POWER = "Oglethorpe Power"
    BSDK_POWER = "BSDK Power"
    TENNESSEE_VALLEY_AUTHORITY = "Tennessee Valley Authority"
    ALTAMAHA_EMC = "Altamaha EMC"
    AMICALOLA_EMC = "Amicalola EMC"
    ABLA_ESPANOL_ELECTRIC = "Abla espanol Electric"
    BLUE_RIDGE_MOUNTAIN_EMC = "Blue Ridge Mountain EMC"
    CANOOCHEE_EMC = "Canoochee EMC"
    CARROLL_EMC = "Carroll EMC"
    CENTRAL_GEORGIA_EMC = "Central Georgia EMC"
    COASTAL_ELECTRIC_COOPERATIVE = "Coastal Electric Cooperative"
    COBB_EMC = "Cobb EMC"
    COLQUITT_EMC = "Colquitt EMC"
    COWETA_FAYETTE_EMC = "Coweta-Fayette EMC"
    DIVERSE_POWER = "Diverse Power Inc."
    DIVERSE_POWER_PATAULA = "Diverse Power Inc. - Pataula District"
    EXCELSIOR_EMC = "Excelsior EMC"
    FLINT_ENERGIES = "Flint Energies"
    GRADY_EMC = "Grady EMC"
    GREYSTONE_POWER = "GreyStone Power Corp."
    HABERSHAM_EMC = "Habersham EMC"
    HART_EMC = "Hart EMC"
    IRWIN_EMC = "Irwin EMC"
    JACKSON_EMC = "Jackson EMC"
    JEFFERSON_ENERGY = "Jefferson Energy Cooperative"
    LITTLE_OCMULGEE_EMC = "Little Ocmulgee EMC"
    MARIETTA_POWER = "Marietta Power"
    MIDDLE_GEORGIA_EMC = "Middle Georgia EMC"
    MITCHELL_EMC = "Mitchell EMC"
    NORTH_GEORGIA_EMC = "North Georgia EMC"
    OCMULGEE_EMC = "Ocmulgee EMC"
    OCONEE_EMC = "Oconee EMC"
    OKEFENOKE_REMC = "Okefenoke REMC"
    PLANTERS_EMC = "Planters EMC"
    RAYLE_EMC = "Rayle EMC"
    SATILLA_REMC = "Satilla REMC"
    SAWNEE_EMC = "Sawnee EMC"
    SLASH_PINE_EMC = "Slash Pine EMC"
    SNAPPING_SHOALS_EMC = "Snapping Shoals EMC"
    SOUTHERN_RIVERS_ENERGY = "Southern Rivers Energy"
    SUMTER_EMC = "Sumter EMC"
    THREE_NOTCH_EMC = "Three Notch EMC"
    TRI_COUNTY_EMC = "Tri-County EMC"
    TRI_STATE_EMC = "Tri-State EMC"
    UPSON_EMC = "Upson EMC"
    WALTON_EMC = "Walton EMC"
    WASHINGTON_EMC = "Washington EMC"
    HAWAIIAN_ELECTRIC = "Hawaiian Electric Company (HECO)"
    HAWAIIAN_ELECTRIC_LIGHT = "Hawaiian Electric Light Company (HELCO)"
    KAUAII_ISLAND_UTILITY = "Kauaʻi Island Utility Cooperative (KIUC)"
    MAUI_ELECTRIC = "Maui Electric Company (MECO)"
    AVISTA = "Avista"
    CLEARWATER_POWER = "Clearwater Power"
    IDACORP = "IDACORP (Idaho Power)"
    PACIFICORP = "PacifiCorp (Rocky Mountain Power)"
    AMEREN = "Ameren"
    ILLINOIS_POWER = "Illinois Power"
    CWLP_SPRINGFIELD = "City Water, Light & Power (Springfield, Illinois)"
    COMED = "ComEd, a subsidiary of Exelon"
    COLES_MOULTRIE_EMC = "Coles Moultrie Electric Cooperative"
    PRAIRIE_STATE_GENERATING = "Prairie State Generating Company"
    SULLIVAN_ELECTRIC = "Sullivan Electric Company"
    AES_INDIANA = "AES Indiana (formerly Indianapolis Power & Light)"
    AEP_INDIANA_MICHIGAN = "American Electric Power (Indiana Michigan Power)"
    CINERGY = "Cinergy Corporation"
    DUKE_ENERGY = "Duke Energy"
    IMPA = "Indiana Municipal Power Agency"
    NISOURCE = "NiSource"
    NIPSCO = "Northern Indiana Public Service Company"
    CENTERPOINT_ENERGY = "CenterPoint Energy (formerly Vectren; formerly Southern Indiana Gas & Electric Company)"
    IPL_ALLIANT_ENERGY = "Interstate Power and Light Company, a part of Alliant Energy"
    MIDAMERICAN_ENERGY = "MidAmerican Energy"
    KCBPU = "Kansas City Board of Public Utilities"
    EVERGY = "Evergy"
    MCPHERSON_BPU = "McPherson BPU"
    AEP = "American Electric Power"
    KENTUCKY_UTILITIES = "Kentucky Utilities"
    LG_E = "Louisville Gas & Electric"
    OWENSBORO_MUNICIPAL_UTILITIES = "Owensboro Municipal Utilities"
    TVA = "Tennessee Valley Authority"
    CLECO = "CLECO"
    SWEPCO = "SWEPCO, a subsidiary of American Electric Power"
    SLEMCO = "SLEMCO"
    SPECTRUM = "SPECTRUM"
    LA_POWER = "Louisiana Power"
    CAJUN_ELECTRIC_COOP = "Cajun Electric Power Co-op"
    CLAIBORNE_ELECTRIC_COOP = "Claiborne Electric Co-op"
    SOUTH_LA_ELECTRIC_COOP = "South Louisiana Electric Co-op"
    NELA_PC = "Northeast Louisiana Power Cooperative"
    BEAUREGARD_ELECTRIC_COOP = "Beauregard Electric Co-op Inc."
    CONCORDIA_ELECTRIC_COOP = "Concordia Electric Co-op"
    JEFFERSON_DAVIS_ELECTRIC_COOP = "Jefferson Davis Electric Co-op"
    WST_ELECTRIC = "WST Electric"
    MERVIN_DANCLAR = "Mervin Danclar Entergy"
    DIXIE_ELECTRIC_MEMBERSHIP_CORP = "Dixie Electric Membership Corp."
    LAFAYETTE_UTILITIES = "Lafayette Utilities System"
    AVANGRID_CMP = "AVANGRID (Central Maine Power)"
    VERSANT_POWER_ENMAX = "Versant Power, a part of ENMAX"
    AN_ELECTRIC_COOPERATIVE = "A&N Electric Cooperative"
    AGWAY_ENERGY_SERVICES = "Agway Energy Services"
    AMBIT_ENERGY = "Ambit Energy"
    BGE_EXELON = "Baltimore Gas and Electric, a subsidiary of Exelon"
    BERLIN_ELECTRIC_UTILITY = "Berlin Electric Utility Department"
    CHAMPION_ENERGY = "Champion Energy"
    CHOPTANK_ELECTRIC_COOPERATIVE = "Choptank Electric Cooperative"
    CONECTIV_PEPCO_EXELON = "Conectiv, a subsidiary of PEPCO which is a subsidiary of Exelon"
    DELMARVA_POWER_EXELON = "Delmarva Power, a subsidiary of Exelon"
    EASTON_UTILITIES = "Easton Utilities"
    FIRSTENERGY_POTOMAC_EDISON = "FirstEnergy (Potomac Edison)"
    HAGERSTOWN_LIGHT_DEPARTMENT = "Hagerstown Light Department"
    JUST_ENERGY = "Just Energy"
    SMECO = "Southern Maryland Electric Cooperative (SMECO)"
    TOWN_OF_THURMONT_MUNICIPAL = "Town of Thurmont Municipal Light Company"
    TOWN_OF_WILLIAMSPORT_UTILITIES = "Town of Williamsport Utilities"
    ASHBURNHAM_MUNICIPAL_LIGHT = "Ashburnham Municipal Light"
    BELMONT_MUNICIPAL_LIGHT = "Belmont Municipal Light"
    BERKSHIRE_WMECO = "Berkshire Company (WMECO)"
    BRAINTREE_ELECTRIC_LIGHT_DEPARTMENT = "Braintree Electric Light Department"
    BOYLSTON_ELECTRIC_LIGHT_DEPARTMENT = "Boylston Electric Light Department"
    CHESTER_MUNICIPAL_ELECTRIC_LIGHT = "Chester Municipal Electric Light"
    CHICOPEE_ELECTRIC_LIGHT_DEPARTMENT = "Chicopee Electric Light Department"
    CONCORD_MUNICIPAL_LIGHT_PLANT = "Concord Municipal Light Plant"
    DANVERS_ELECTRIC_DEPARTMENT = "Danvers Electric Department"
    EVERSOURCE_NSTAR_WMECO = "Eversource Energy (NSTAR, Western Massachusetts Electric)"
    FAIRFIELD_ELECTRIC_COOPERATIVE = "Fairfield Electric cooperative"
    GEORGETOWN_ELECTRIC_DEPARTMENT = "Georgetown Electric Department"
    GOSNOLD_MUNICIPAL_ELECTRIC_PLANT = "Gosnold Municipal Electric Plant"
    GROTON_ELECTRIC_DEPARTMENT = "Groton Electric Department"
    GROVELAND_LIGHT_DEPARTMENT = "Groveland Light Department"
    HINGHAM_MUNICIPAL_LIGHT_DEPARTMENT = "Hingham Municipal Light Department"
    HOLDEN_MUNICIPAL_LIGHT_DEPARTMENT = "Holden Municipal Light Department"
    HOLYOKE_GAS_ELECTRIC = "Holyoke Gas and Electric"
    HUDSON_LIGHT_WATER_DEPARTMENT = "Hudson Light and Water Department"
    HULL_ELECTRIC_LIGHT_DEPARTMENT = "Hull Electric Light Department"
    IPSWICH_ELECTRIC_LIGHT_DEPARTMENT = "Ipswich Electric Light Department"
    LITTLETON_ELECTRIC_LIGHT_WATER_DEPARTMENT = "Littleton Electric Light and Water Department"
    MARBLEHEAD_MUNICIPAL_LIGHT_DEPARTMENT = "Marblehead Municipal Light Department"
    MANSFIELD_MUNICIPAL_LIGHT_DEPARTMENT = "Mansfield Municipal Light Department"
    MERRIMAC_LIGHT_WATER_DEPARTMENT = "Merrimac Light and Water Department"
    MIDDLEBORO_MUNICIPAL_GAS_ELECTRIC_DEPARTMENT = "Middleboro Municipal Gas and Electric Department"
    MIDDLETON_MUNICIPAL_LIGHT_DEPARTMENT = "Middleton Municipal Light Department"
    NATIONAL_GRID_MASSACHUSETTS_NANTUCKET = "National Grid (Massachusetts Electric, Nantucket Electric)"
    NORTH_ATTLEBORO_ELECTRIC_DEPARTMENT = "North Attleboro Electric Department"
    NORWOOD_ELECTRIC_LIGHT_DEPARTMENT = "Norwood Electric Light Department"
    NSTAR = "NSTAR"
    PAXTON_MUNICIPAL_LIGHT_DEPARTMENT = "Paxton Municipal Light Department"
    PEABODY_MUNICIPAL_LIGHT_PLANT = "Peabody Municipal Light Plant"
    PRINCETON_ELECTRIC_LIGHT_DEPARTMENT = "Princeton Electric Light Department"
    READING_MUNICIPAL_LIGHT_DEPARTMENT = "Reading Municipal Light Department"
    ROWLEY_ELECTRIC_LIGHT_DEPARTMENT = "Rowley Electric Light Department"
    RUSSELL_MUNICIPAL_LIGHT_DEPARTMENT = "Russell Municipal Light Department"
    SHREWSBURY_ELECTRIC_LIGHT_DEPARTMENT = "Shrewsbury Electric Light Department"
    SOUTH_HADLEY_ELECTRIC_LIGHT_DEPARTMENT = "South Hadley Electric Light Department"
    STERLING_ELECTRIC_LIGHT_DEPARTMENT = "Sterling Electric Light Department"
    TAUNTON_MUNICIPAL_LIGHT_PLANT = "Taunton Municipal Light Plant"
    TEMPLETON_MUNICIPAL_LIGHT_COMPANY = "Templeton Municipal Light Company"
    WAKEFIELD_MUNICIPAL_GAS_LIGHT_DEPARTMENT = "Wakefield Municipal Gas and Light Department"
    WELLESLEY_MUNICIPAL_LIGHT_PLANT = "Wellesley Municipal Light Plant"
    WEST_BOYLSTON_MUNICIPAL_LIGHTING = "West Boylston Municipal Lighting"
    WESTFIELD_GAS_ELECTRIC_DEPARTMENT = "Westfield Gas and Electric Department"
    PTI_ELECTRIC_DEPARTMENT = "PTI Electric Department"
    ALGER_DELTA_ELECTRIC_COOPERATIVE = "Alger Delta Electric Cooperative"
    ALPENA_POWER_COMPANY = "Alpena Power Company"
    AEP_IND_MICHIGAN_POWER = "American Electric Power (Indiana Michigan Power)"
    CHERRYLAND_ELECTRIC_COOPERATIVE = "Cherryland Electric Cooperative"
    CLOVERLAND_ELECTRIC_COOPERATIVE = "Cloverland Electric Cooperative"
    CONSUMERS_ENERGY = "Consumers Energy"
    DTE_ENERGY = "DTE Energy (DTE Energy Electric Company)"
    GREAT_LAKES_ENERGY_COOPERATIVE = "Great Lakes Energy Cooperative"
    HOLLAND_BOARD_OF_PUBLIC_WORKS = "Holland Board of Public Works"
    HOMEWORKS_TRI_COUNTY_ELECTRIC_COOPERATIVE = "Homeworks Tri-County Electric Cooperative"
    LANSING_BOARD_OF_WATER_LIGHT = "Lansing Board of Water & Light"
    LOWELL_LIGHT_POWER = "Lowell Light and Power"
    MIDWEST_ENERGY_COMMUNICATIONS_COOPERATIVE = "Midwest Energy & Communications (Cooperative)"
    ONTONAGON_COUNTY_REA_COOPERATIVE = "Ontonagon County REA (Cooperative)"
    PRESQUE_ISLE_ELECTRIC_GAS_COOPERATIVE = "Presque Isle Electric & Gas Cooperative"
    THUMB_ELECTRIC_COOPERATIVE = "Thumb Electric Cooperative"
    UPPER_PENINSULA_POWER_COMPANY = "Upper Peninsula Power Company"
    WE_ENERGIES = "We Energies"
    WYANDOTTE_MUNICIPAL_SERVICES = "Wyandotte Municipal Services"
    BASIN_ELECTRIC_POWER_COOPERATIVE = "Basin Electric Power Cooperative"
    DAIRYLAND_POWER_COOP = "Dairyland Power Coop"
    EAST_RIVER_ELECTRIC_POWER_COOP = "East River Electric Power Co-op"
    FREEBORN_MOWER_COOP_SERVICES = "Freeborn-Mower Co-op Services"
    GREAT_RIVER_ENERGY = "Great River Energy"
    HUTCHINSON_UTILITIES_COMMISSION = "Hutchinson Utilities Commission"
    INTERSTATE_POWER_AND_LIGHT_COMPANY = "Interstate Power and Light Company"
    LO_POWER_COOP = "L&O Power Co-op"
    MARSHALL_MUNICIPAL_UTILITIES = "Marshall Municipal Utilities"
    MINNKOTA_POWER_COOPERATIVE = "Minnkota Power Cooperative"
    MINNESOTA_POWER = "Minnesota Power"
    MISSOURI_RIVER_ENERGY = "Missouri River Energy"
    NORTHERN_STATES_POWER_COMPANY = "Northern States Power Company"
    PEOPLES_COOP_TRI_COUNTY_ELECTRIC = "People's Co-op Tri-County Electric"
    ROCHESTER_PUBLIC_UTILITIES_COMMISSION = "Rochester Public Utilities Commission"
    SOUTHERN_MINNESOTA_MUNICIPAL_POWER_AGENCY = "Southern Minnesota Municipal Power Agency"
    WILLMAR_MUNICIPAL_UTILITIES = "Willmar Municipal Utilities"
    ENTERGY_MISSISSIPPI = "Entergy Mississippi"
    MAGNOLIA_ELECTRIC_POWER = "Magnolia Electric Power"
    MISSISSIPPI_POWER = "Mississippi Power"
    COOPERATIVE_ENERGY = "Cooperative Energy"
    PEARL_RIVER_VALLEY_EPA = "Pearl River Valley EPA"
    YAZOO_VALLEY_ELECTRIC_POWER_ASSOCIATION = "Yazoo Valley Electric Power Association"
    AQUILA = "Aquila"
    BLACK_RIVER_ELECTRIC_COOPERATIVE = "Black River Electric Cooperative"
    CITY_OF_COLUMBIA_WATER_AND_LIGHT = "City of Columbia Water and Light"
    CITY_UTILITIES_OF_SPRINGFIELD = "City Utilities of Springfield"
    HANNIBAL_MISSOURI = "Hannibal, Missouri"
    CITIZENS_ELECTRIC_CORPORATION = "Citizens Electric Corporation"
    EMPIRE_DISTRICT_ELECTRIC_COMPANY = "Empire District Electric Company"
    INDEPENDENCE_POWER_AND_LIGHT = "Independence Power and Light"
    INTERCOUNTY_ELECTRIC_COOPERATIVE_ASSOCIATION = "Intercounty Electric Cooperative Association"
    CUIVRE_RIVER_ELECTRIC_COOPERATIVE = "Cuivre River Electric Cooperative"
    KANSAS_CITY_POWER_AND_LIGHT_COMPANY = "Kansas City Power and Light Company"
    LACLEDE_ELECTRIC_COOPERATIVE = "Laclede Electric Cooperative"
    MACON_ELECTRIC_COOPERATIVE = "Macon Electric Cooperative"
    MISSOURI_RURAL_ELECTRIC_COOPERATIVE = "Missouri Rural Electric Cooperative"
    NORTH_CENTRAL_MISSOURI_ELECTRIC_COOPERATIVE = "North Central Missouri Electric Cooperative"
    HOWELL_OREGON_ELECTRIC_COOPERATIVE = "Howell-Oregon Electric Cooperative"
    OZARK_BORDER_ELECTRIC_COOPERATIVE = "Ozark Border Electric Cooperative"
    SEMO_ELECTRIC_COOPERATIVE = "Semo Electric Cooperative"
    SA_MA_NO_ELECTRIC_COOPERATIVE = "Sa-Ma-No Electric Cooperative"
    WHITE_RIVER_VALLEY_ELECTRIC_COOPERATIVE = "White River Valley Electric Cooperative"
    CENTRAL_MONTANA_ELECTRIC_POWER_COOPERATIVE = "Central Montana Electric Power Cooperative"
    MONTANA_DAKOTA_UTILITIES_MDU = "Montana-Dakota Utilities (MDU)"
    MONTANA_ELECTRIC_COOPERATIVES_ASSOCIATION = "Montana Electric Cooperatives' Association"
    NORTHWESTERN_ENERGY = "Northwestern Energy"
    NEBRASKA_PUBLIC_POWER_DISTRICT = "Nebraska Public Power District"
    OMAHA_PUBLIC_POWER_DISTRICT = "Omaha Public Power District"
    LINCOLN_ELECTRIC_SYSTEM = "Lincoln Electric System"
    FREMONT_DEPARTMENT_OF_UTILITIES = "Fremont Department of Utilities"
    NV_ENERGY_NEVADA_POWER = "NV Energy (Nevada Power)"
    NEXTERA_VALLEY_ELECTRIC_ASSOCIATION = "NextEra (Valley Electric Association)"
    WELLS_RURAL_ELECTRIC_COMPANY = "Wells Rural Electric Company"
    BOULDER_CITY_ELECTRIC_UTILITY = "Boulder City Electric Utility"
    HARNEY_ELECTRIC_COOPERATIVE = "Harney Electric Cooperative"
    LINCOLN_COUNTY_POWER = "Lincoln County Power"
    MT_WHEELER_POWER = "Mt Wheeler Power"
    OVERTON_POWER = "Overton Power"
    PLUMAS_SIERRA_ELECTRIC_COOPERATIVE = "Plumas Sierra Electric Cooperative"
    SURPRISE_VALLEY_ELECTRIC_COOPERATIVE = "Surprise Valley Electric Cooperative"
    EVERSOURCE_ENERGY_PUBLIC_SERVICE_COMPANY_NH = "Eversource Energy (Public Service Company of New Hampshire)"
    LIBERTY_UTILITIES_GRANITE_STATE_ELECTRIC = "Liberty Utilities (including Granite State Electric)"
    NEW_HAMPSHIRE_ELECTRIC_COOPERATIVE = "New Hampshire Electric Cooperative"
    NATIONAL_GRID = "National Grid"
    UNITIL_CORPORATION = "Unitil Corporation"
    ATLANTIC_CITY_ELECTRIC_EXELON = "Atlantic City Electric, a subsidiary of Exelon"
    JERSEY_CENTRAL_POWER_AND_LIGHT_COMPANY = "Jersey Central Power and Light Company, a subsidiary of FirstEnergy"
    PUBLIC_SERVICE_ELECTRIC_AND_GAS_COMPANY_PSEG = "Public Service Electric and Gas Company (PSE&G)"
    ROCKLAND_ELECTRIC_ORANGE_ROCKLAND_CONSOLIDATED_EDISON = "Rockland Electric, a subsidiary of Orange and Rockland, which is a subsidiary of Consolidated Edison"
    BOROUGH_OF_MADISON_ELECTRIC_UTILITY = "Borough of Madison Electric Utility"
    BOROUGH_OF_MILLTOWN_ELECTRIC_DEPARTMENT = "Borough of Milltown Electric Department"
    BOROUGH_OF_PARK_RIDGE_ELECTRIC_DEPARTMENT = "Borough of Park Ridge Electric Department"
    BOROUGH_OF_SEASIDE_HEIGHTS_ELECTRIC_UTILITY = "Borough of Seaside Heights Electric Utility"
    BOROUGH_OF_SOUTH_RIVER_ELECTRIC_DEPARTMENT = "Borough of South River Electric Department"
    BUTLER_POWER_AND_LIGHT = "Butler Power and Light"
    LAVALLETTE_ELECTRIC_DEPARTMENT = "Lavallette Electric Department"
    PEMBERON_BOROUGH_ELECTRIC_DEPARTMENT = "Pemberton Borough Electric Department"
    SUSSEX_RURAL_ELECTRIC_COOPERATIVE = "Sussex Rural Electric Cooperative"
    VINELAND_MUNICIPAL_ELECTRIC_UTILITY = "Vineland Municipal Electric Utility"
    EL_PASO_ELECTRIC = "El Paso Electric"
    PUBLIC_SERVICE_COMPANY_OF_NEW_MEXICO = "Public Service Company of New Mexico"
    TRI_STATE_GENERATION_AND_TRANSMISSION_ASSOCIATION = "Tri-State Generation and Transmission Association"
    AKRON_MUNICIPAL_ELECTRIC_DEPARTMENT = "Akron Municipal Electric Department"
    ANGELICA_MUNICIPAL_ELECTRIC_DEPARTMENT = "Angelica Municipal Electric Department"
    APPROVED_ENERGY = "Approved Energy"
    BATH_MUNICIPAL_ELECTRIC_DEPARTMENT = "Bath Municipal Electric Department"
    BERGEN_MUNICIPAL_ELECTRIC_DEPARTMENT = "Bergen Municipal Electric Department"
    BOONVILLE_MUNICIPAL_ELECTRIC_DEPARTMENT = "Boonville Municipal Electric Department"
    BROCTON_MUNICIPAL_ELECTRIC_DEPARTMENT = "Brocton Municipal Electric Department"
    CASTLE_MUNICIPAL_ELECTRIC_DEPARTMENT = "Castle Municipal Electric Department"
    CENTRAL_HUDSON_GAS_ELECTRIC = "Central Hudson Gas & Electric"
    CH_ENERGY_GROUP = "CH Energy Group"
    CHURCHVILLE_MUNICIPAL_ELECTRIC_DEPARTMENT = "Churchville Municipal Electric Department"
    CONSOLIDATED_EDISON_COMPANY_OF_NEW_YORK = "Consolidated Edison Company of New York, subsidiary of Consolidated Edison"
    EAST_COAST_POWER_GAS = "East Coast Power & Gas"
    FISHERS_ISLAND_MUNICIPAL_ELECTRIC_DEPARTMENT = "Fishers Island Municipal Electric Department"
    FRANKFORT_MUNICIPAL_ELECTRIC_DEPARTMENT = "Frankfort Municipal Electric Department"
    FREEPORT_ELECTRIC_DEPARTMENT = "Freeport Electric Department"
    GREEN_ISLAND_MUNICIPAL_ELECTRIC_DEPARTMENT = "Green Island Municipal Electric Department"
    GREENPORT_MUNICIPAL_ELECTRIC_DEPARTMENT = "Greenport Municipal Electric Department"
    GREENE_MUNICIPAL_ELECTRIC_DEPARTMENT = "Greene Municipal Electric Department"
    GROTON_MUNICIPAL_ELECTRIC_DEPARTMENT = "Groton Municipal Electric Department"
    HAMILTON_MUNICIPAL_ELECTRIC_DEPARTMENT = "Hamilton Municipal Electric Department"
    ILLION_MUNICIPAL_ELECTRIC_DEPARTMENT = "Ilion Municipal Electric Department"
    JAMESTOWN_MUNICIPAL_ELECTRIC_DEPARTMENT = "Jamestown Municipal Electric Department"
    LAKE_PLACID_MUNICIPAL_ELECTRIC_DEPARTMENT = "Lake Placid Municipal Electric Department"
    LONG_ISLAND_POWER_AUTHORITY = "Long Island Power Authority (LIPA), operated by PSEG Long Island"
    MARATHON_MUNICIPAL_ELECTRIC_DEPARTMENT = "Marathon Municipal Electric Department"
    MASSENA_ELECTRIC_DEPARTMENT = "Massena Electric Department"
    MAYVILLE_MUNICIPAL_ELECTRIC_DEPARTMENT = "Mayville Municipal Electric Department"
    NATIONAL_GRID_NIAGARA_MOHAWK = "National Grid (Niagara Mohawk)"
    NEW_YORK_POWER_AUTHORITY = "New York Power Authority (NYPA)"
    NEW_YORK_STATE_ELECTRIC_GAS = "New York State Electric & Gas, subsidiary of AVANGRID"
    ORANGE_AND_ROCKLAND = "Orange and Rockland, which is a subsidiary of Consolidated Edison"
    PENN_YAN_MUNICIPAL_ELECTRIC_DEPARTMENT = "Penn Yan Municipal Electric Department"
    PHILADELPHIA_MUNICIPAL_ELECTRIC_DEPARTMENT = "Philadelphia Municipal Electric Department"
    PLATTSBURGH_MUNICIPAL_LIGHT_DEPARTMENT = "Plattsburgh Municipal Light Department"
    ROCHESTER_GAS_ELECTRIC = "Rochester Gas & Electric, subsidiary of AVANGRID"
    ROCKVILLE_CENTRE_MUNICIPAL_ELECTRIC_DEPARTMENT = "Rockville Centre Municipal Electric Department"
    ROUSES_POINT_ELECTRIC_DEPARTMENT = "Rouses Point Electric Department"
    SALAMANCA_MUNICIPAL_ELECTRIC_DEPARTMENT = "Salamanca Municipal Electric Department"
    SHERBURNE_MUNICIPAL_ELECTRIC_DEPARTMENT = "Sherburne Municipal Electric Department"
    SHERRILL_MUNICIPAL_ELECTRIC_DEPARTMENT = "Sherrill Municipal Electric Department"
    SKANEATELES_MUNICIPAL_ELECTRIC_DEPARTMENT = "Skaneateles Municipal Electric Department"
    SLIVER_SPRINGS_MUNICIPAL_ELECTRIC_DEPARTMENT = "Sliver Springs Municipal Electric Department"
    SOLVAY_ELECTRIC_DEPARTMENT = "Solvay Electric Department"
    SPENCERPORT_MUNICIPAL_ELECTRIC_DEPARTMENT = "Spencerport Municipal Electric Department"
    SPRINGVILLE_MUNICIPAL_ELECTRIC_DEPARTMENT = "Springville Municipal Electric Department"
    THERESA_MUNICIPAL_ELECTRIC_DEPARTMENT = "Theresa Municipal Electric Department"
    TUPPER_LAKE_MUNICIPAL_ELECTRIC_DEPARTMENT = "Tupper Lake Municipal Electric Department"
    WATKINS_GLEN_MUNICIPAL_ELECTRIC_DEPARTMENT = "Watkins Glen Municipal Electric Department"
    WAVERLY_MUNICIPAL_ELECTRIC_DEPARTMENT = "Waverly Municipal Electric Department"
    WELLsville_MUNICIPAL_ELECTRIC_DEPARTMENT = "Wellsville Municipal Electric Department"
    WESTFIELD_MUNICIPAL_ELECTRIC_DEPARTMENT = "Westfield Municipal Electric Department"
    ALBEMARLE_ELECTRIC_MEMBERSHIP_CORPORATION = "Albemarle Electric Membership Corporation"
    BLUE_RIDGE_ENERGY = "Blue Ridge Energy"
    BRUNSWICK_ELECTRIC_MEMBERSHIP_CORPORATION = "Brunswick Electric Membership Corporation"
    CAPE_HATTERAS_ELECTRIC_COOPERATIVE = "Cape Hatteras Electric Cooperative"
    CARTERET_CRAVEN_ELECTRIC_COOPERATIVE = "Carteret-Craven Electric Cooperative"
    CENTRAL_ELECTRIC_MEMBERSHIP_CORPORATION = "Central Electric Membership Corporation"
    CITY_OF_APEX_ELECTRIC_DEPARTMENT = "City of Apex Electric Department"
    CITY_OF_CONCORD_ELECTRIC_DEPARTMENT = "City of Concord Electric Department"
    DOMINION_NORTH_CAROLINA_POWER = "Dominion North Carolina Power"
    EDGE_COMBE_MARTIN_COUNTY_ELECTRIC_MEMBERSHIP_CORPORATION = "Edgecombe-Martin County Electric Membership Corporation"
    ENERGYUNITED = "EnergyUnited"
    FOUR_COUNTY_ELECTRIC_MEMBERSHIP_CORPORATION = "Four County Electric Membership Corporation"
    FRENCH_BROAD_ELECTRIC_MEMBERSHIP_CORPORATION = "French Broad Electric Membership Corporation"
    HALIFAX_ELECTRIC_MEMBERSHIP_CORPORATION = "Halifax Electric Membership Corporation"
    HAYWOOD_ELECTRIC_MEMBERSHIP_CORPORATION = "Haywood Electric Membership Corporation"
    JONES_ONSLOW_ELECTRIC_MEMBERSHIP_CORPORATION = "Jones-Onslow Electric Membership Corporation"
    LUMBEE_RIVER_ELECTRIC_MEMBERSHIP_CORPORATION = "Lumbee River Electric Membership Corporation"
    NORTH_CAROLINA_ELECTRIC_MEMBERSHIP_CORPORATION = "North Carolina Electric Membership Corporation"
    PEE_DEE_ELECTRIC_MEMBERSHIP_CORPORATION = "Pee Dee Electric Membership Corporation"
    PIEDMONT_ELECTRIC_MEMBERSHIP_CORPORATION = "Piedmont Electric Membership Corporation"
    PIT_GREENE_ELECTRIC_MEMBERSHIP_CORPORATION = "Pitt & Greene Electric Membership Corporation"
    RANDOLPH_ELECTRIC_MEMBERSHIP_CORPORATION = "Randolph Electric Membership Corporation"
    ROANOKE_ELECTRIC_COOPERATIVE = "Roanoke Electric Cooperative"
    RUTHERFORD_ELECTRIC_MEMBERSHIP_CORPORATION = "Rutherford Electric Membership Corporation"
    SOUTH_RIVER_ELECTRIC_MEMBERSHIP_CORPORATION = "South River Electric Membership Corporation"
    SURRY_YADKIN_ELECTRIC_MEMBERSHIP_CORPORATION = "Surry-Yadkin Electric Membership Corporation"
    TIDELAND_ELECTRIC_MEMBERSHIP_CORPORATION = "Tideland Electric Membership Corporation"
    TRI_COUNTY_ELECTRIC_MEMBERSHIP_CORPORATION = "Tri-County Electric Membership Corporation"
    UNION_POWER_COOPERATIVE = "Union Power Cooperative"
    WAKE_ELECTRIC_MEMBERSHIP_CORPORATION = "Wake Electric Membership Corporation"
    CENTRAL_POWER_ELECTRIC_COOPERATIVE = "Central Power Electric Cooperative"
    MONTANA_DAKOTA_UTILITIES = "Montana Dakota Utilities (MDU)"
    UPPER_MISSOURI_POWER_COOPERATIVE = "Upper Missouri Power Cooperative (Upper Missouri G&T Cooperative)"
    XCEL_ENERGY = "Xcel Energy"
    AMERICAN_ELECTRIC_POWER = "American Electric Power"
    CONSOLIDATED_ELECTRIC_COOPERATIVE = "Consolidated Electric Cooperative"
    DAYTON_POWER_LIGHT = "Dayton Power & Light"
    SOUTH_CENTRAL_POWER_COMPANY = "South Central Power Company"
    EAST_CENTRAL_ELECTRIC_COOPERATIVE = "East Central Electric Cooperative"
    OKLAHOMA_GAS_ELECTRIC = "Oklahoma Gas & Electric"
    PUBLIC_SERVICE_COMPANY_OF_OKLAHOMA = "Public Service Company of Oklahoma (part of American Electric Power)"
    WESTERN_FARMERS_ELECTRIC_COOPERATIVE = "Western Farmers Electric Cooperative"
    BLACHLY_LANE_ELECTRIC_COOPERATIVE = "Blachly-Lane Electric Cooperative"
    CENTRAL_LINCOLN_PUD = "Central Lincoln PUD"
    CLATSKANIE_PUD = "Clatskanie PUD"
    COLUMBIA_RIVER_PUD = "Columbia River PUD"
    CONSUMERS_POWER_INC = "Consumers Power Inc."
    COOS_CURRY_ELECTRIC_COOP = "Coos-Curry Electric Coop"
    DOUGLAS_ELECTRIC_COOPERATIVE = "Douglas Electric Cooperative"
    EMERALD_PUD = "Emerald PUD"
    EUGENE_WATER_ELECTRIC_BOARD = "Eugene Water & Electric Board (EWEB)"
    HOOD_RIVER_ELECTRIC_INTERNET_COOP = "Hood River Electric & Internet Co-op"
    LANE_ELECTRIC_COOPERATIVE = "Lane Electric Cooperative"
    MIDSTATE_ELECTRIC_COOPERATIVE = "Midstate Electric Cooperative"
    NORTHERN_WASCO_COUNTY_PUD = "Northern Wasco County PUD"
    PORTLAND_GENERAL_ELECTRIC = "Portland General Electric"
    SALEM_ELECTRIC = "Salem Electric"
    SPRINGFIELD_UTILITY_BOARD = "Springfield Utility Board"
    TILLAMOOK_PUD = "Tillamook PUD"
    WEST_OREGON_ELECTRIC_COOPERATIVE = "West Oregon Electric Cooperative"
    UMATILLA_ELECTRIC_COOPERATIVE = "Umatilla Electric Cooperative"
    ADAMS_ELECTRIC_COOPERATIVE = "Adams Electric Cooperative"
    ALLEGHENY_ELECTRIC_COOPERATIVE = "Allegheny Electric Cooperative"
    BEDFORD_RURAL_ELECTRIC_COOPERATIVE = "Bedford Rural Electric Cooperative"
    BOROUGH_OF_EPHRATA_ELECTRIC_DIVISION = "Borough of Ephrata Electric Division"
    BOROUGH_OF_HATFIELD_ELECTRIC_UTILITY = "Borough of Hatfield Electric Utility"
    BOROUGH_OF_KUTZTOWN_ELECTRIC_DEPARTMENT = "Borough of Kutztown Electric Department"
    BOROUGH_OF_QUAKERTOWN_ELECTRIC_DEPARTMENT = "Borough of Quakertown Electric Department"
    BOROUGH_OF_SCHUYLKILL_HAVEN_UTILITIES_DEPARTMENT = "Borough of Schuylkill Haven Utilities Department"
    CENTRAL_ELECTRIC_COOPERATIVE = "Central Electric Cooperative"
    CITIZENS_ELECTRIC_COMPANY = "Citizen's Electric Company"
    CLAVERACK_RURAL_ELECTRIC_COOPERATIVE = "Claverack Rural Electric Cooperative"
    DUQUESNE_LIGHT = "Duquesne Light"
    FIRSTENERGY = "FirstEnergy (Met-Ed, Penelec, Penn Power, West Penn Power)"
    LANSDAL_ELECTRIC = "Lansdale Electric"
    NEW_ENTERPRISE_RURAL_ELECTRIC_COOPERATIVE = "New Enterprise Rural Electric Cooperative"
    NORTHWESTERN_RURAL_ELECTRIC_COOPERATIVE = "Northwestern Rural Electric Cooperative"
    PECO = "PECO, a subsidiary of Exelon"
    PERKASIE_BOROUGH_ELECTRIC_DEPARTMENT = "Perkasie Borough Electric Department"
    PIKE_COUNTY_LIGHT_AND_POWER = "Pike County Light & Power"
    PPL_CORPORATION = "PPL Corporation"
    REA_ENERGY_COOPERATIVE = "REA Energy Cooperative"
    RURAL_VALLEY_ELECTRIC_CO = "Rural Valley Electric Co."
    SOMERSET_RURAL_ELECTRIC_COOPERATIVE = "Somerset Rural Electric Cooperative"
    SULLIVAN_COUNTY_RURAL_ELECTRIC_COOPERATIVE = "Sullivan County Rural Electric Cooperative"
    TRI_COUNTY_RURAL_ELECTRIC_COOPERATIVE = "Tri-County Rural Electric Cooperative"
    UGI_UTILITIES = "UGI Utilities"
    UNITED_ELECTRIC_COOPERATIVE = "United Electric Cooperative"
    VALLEY_RURAL_ELECTRIC_COOPERATIVE = "Valley Rural Electric Cooperative"
    WARREN_ELECTRIC_COOPERATIVE = "Warren Electric Cooperative"
    WELLSTBORO_ELECTRIC_COMPANY = "Wellsboro Electric Company"
    PUERTO_RICO_ELECTRIC_POWER_AUTHORITY = "Puerto Rico Electric Power Authority"
    ECOELECTRICA = "EcoEléctrica"
    RHODE_ISLAND_ENERGY = "Rhode Island Energy"
    PASCOAG_UTILITY_DISTRICT = "Pascoag Utility District"
    AIKEN_ELECTRIC_CO_OP = "Aiken Electric Co-Op"
    BERKELEY_ELECTRIC_CO_OP = "Berkeley Electric Co-Op"
    BLACK_RIVER_ELECTRIC_CO_OP = "Black River Electric Co-op"
    BLUE_RIDGE_ELECTRIC_CO_OP = "Blue Ridge Electric Co-op"
    BROAD_RIVER_ELECTRIC_CO_OP = "Broad River Electric Co-op"
    CENTRAL_ELECTRIC_POWER_COOPERATIVE_INC = "Central Electric Power Cooperative, Inc."
    COASTAL_ELECTRIC_CO_OP = "Coastal Electric Co-op"
    EDISTO_ELECTRIC_CO_OP = "Edisto Electric Co-op"
    FAIRFIELD_ELECTRIC_CO_OP = "Fairfield Electric Co-op"
    HORRY_ELECTRIC_CO_OP = "Horry Electric Co-op"
    LAURENS_ELECTRIC_CO_OP = "Laurens Electric Co-op"
    LITTLE_RIVER_ELECTRIC_CO_OP = "Little River Electric Co-op"
    LYNCHES_RIVER_ELECTRIC_CO_OP = "Lynches River Electric Co-op"
    MID_CAROLINA_ELECTRIC_CO_OP = "Mid-Carolina Electric Co-op"
    NEWBERRY_ELECTRIC_CO_OP = "Newberry Electric Co-op"
    PALMETTO_ELECTRIC_CO_OP = "Palmetto Electric Co-op"
    PROGRESS_ENERGY_CAROLINAS = "Progress Energy Carolinas"
    SANTEE_COOPER = "Santee Cooper"
    SANTEE_ELECTRIC_CO_OP = "Santee Electric Co-op"
    DOMINION_ENERGY = "Dominion Energy"
    TRI_COUNTY_ELECTRIC_CO_OP = "Tri-County Electric Co-Op"
    YORK_ELECTRIC_CO_OP = "York Electric Co-op"
    EAST_RIVER_ELECTRIC_COOPERATIVE = "East River Electric Cooperative"
    MIDAMERICAN_ENERGY_COMPANY = "MidAmerican Energy Company"
    NORTHERN_STATES_POWER = "Northern States Power Company, a subsidiary of Xcel Energy"
    OTTER_TAIL_POWER_COMPANY = "Otter Tail Power Company"
    RUSHMORE_ELECTRIC_COOPERATIVE = "Rushmore Electric Cooperative"
    CHICKASAW_ELECTRIC_COOPERATIVE = "Chickasaw Electric Cooperative"
    CITIZENS_UTILITIES_BOARD = "Citizens Utilities Board"
    EPB_CHATTANOOGA_HAMILTON_COUNTY = "EPB (Electric Power Board), Chattanooga, Hamilton County"
    KNOXVILLE_UTILITIES_BOARD = "Knoxville Utilities Board"
    LENOIR_CITY_UTILITIES_BOARD = "Lenoir City Utilities Board"
    MEMPHIS_LIGHT_GAS_AND_WATER = "Memphis Light, Gas and Water"
    MIDDLE_TENNESSEE_ELECTRIC_COOPERATIVE = "Middle Tennessee Electric, Electric Cooperative"
    NASHVILLE_ELECTRIC_SERVICE = "Nashville Electric Service, metro Nashville, Davidson County"
    AUSTIN_ENERGY = "Austin Energy"
    AMIGO_ENERGY = "Amigo Energy"
    SOUTH_WEST_ENERGY = "South West Energy"
    BARTLETT_ELECTRIC_COOPERATIVE = "Bartlett Electric Cooperative"
    BRAZOS_ELECTRIC_POWER_COOPERATIVE = "Brazos Electric Power Cooperative"
    CITY_OF_BRYAN = "City of Bryan"
    CITY_OF_GREENVILLE = "City of Greenville"
    COMANCHE_ELECTRIC_COOPERATIVE = "Comanche Electric Cooperative"
    COSERV_ELECTRIC = "CoServ Electric"
    COSERY_ELECTRIC = "Cosery Electric"
    CPS_ENERGY = "CPS Energy"
    DENTON_MUNICIPAL_ELECTRIC = "Denton Municipal Electric"
    DIRECT_ENERGY = "Direct Energy"
    DPI_ENERGY = "dPi Energy"
    ELECTRIC_DATABASE_PUBLISHING = "Electric Database Publishing"
    ENTERGY = "Entergy"
    ENTRUST_ENERGY = "Entrust Energy"
    FIRST_TEXAS_ENERGY_CORPORATION = "First Texas Energy Corporation"
    FORT_BELKNAP_ELECTRIC_COOPERATIVE = "Fort Belknap Electric Cooperative"
    GARLAND_POWER_LIGHT = "Garland Power & Light"
    GDF_SUEZ_ENERGY_RESOURCES = "GDF SUEZ Energy Resources"
    GOLDEN_SPREAD_ELECTRIC_COOPERATIVE = "Golden Spread Electric Cooperative"
    HUDSON_ENERGY = "Hudson Energy"
    HAMILTON_COUNTY_ELECTRIC_COOPERATIVE = "Hamilton County Electric Cooperative"
    HEART_OF_TEXAS_ELECTRIC_COOPERATIVE = "Heart of Texas Electric Cooperative"
    HILCO_ELECTRIC_COOPERATIVE = "HILCO Electric Cooperative"
    JAC_ELECTRIC_COOPERATIVE = "J-A-C Electric Cooperative"
    LOWER_COLORADO_RIVER_AUTHORITY = "Lower Colorado River Authority"
    LUMINANT = "Luminant"
    MIDSOUTH_SYNERGY = "MidSouth Synergy"
    NAVARRO_COUNTY_ELECTRIC_COOPERATIVE = "Navarro County Electric Cooperative"
    NAVASOTA_VALLEY_ELECTRIC_COOPERATIVE = "Navasota Valley Electric Cooperative"
    ONCOR_ELECTRIC_DELIVERY = "Oncor Electric Delivery (Formerly TXU)"
    PEDERNALES_ELECTRIC_COOPERATIVE = "Pedernales Electric Cooperative"
    PENTEX_ENERGY = "PenTex Energy"
    RAYBURN_ELECTRIC_COOPERATIVE = "Rayburn Electric Cooperative"
    RELIANT_ENERGY = "Reliant Energy"
    SOUTH_PLAINS_ELECTRIC_COOPERATIVE = "South Plains Electric Cooperative"
    SOUTHWESTERN_PUBLIC_SERVICE_COMPANY = "Southwestern Public Service Company, a subsidiary of Xcel Energy"
    TEXAS_ELECTRIC_SERVICE_COMPANY = "Texas Electric Service Company"
    TEXAS_NEW_MEXICO_POWER = "Texas New Mexico Power"
    TARA_ENERGY = "Tara Energy"
    TRI_COUNTY_ELECTRIC_COOPERATIVE = "Tri-County Electric Cooperative"
    TXU_ENERGY = "TXU Energy"
    UNITED_COOPERATIVE_SERVICES = "United Cooperative Services"
    WISE_ELECTRIC_COOPERATIVE = "Wise Electric Cooperative"
    CITY_OF_BOUNTIFUL = "City of Bountiful"
    IPA = "IPA"
    CITY_OF_KAYSVILLE = "City of Kaysville"
    PACIFICORP_ROCKY_MOUNTAIN_POWER = "PacifiCorp (Rocky Mountain Power)"
    PACIFICORP_DOMINION_ENERGY = "PacifiCorp (Dominion Energy)"
    BURLINGTON_ELECTRIC_DEPARTMENT = "Burlington Electric Department"
    GREEN_MOUNTAIN_POWER = "Green Mountain Power"
    VERMONT_ELECTRIC_COOPERATIVE = "Vermont Electric Cooperative"
    WASHINGTON_ELECTRIC_COOPERATIVE = "Washington Electric Cooperative"
    APPALACHIAN_POWER = "Appalachian Power, a subsidiary of American Electric Power"
    BARC_ELECTRIC_COOPERATIVE = "BARC Electric Cooperative"
    COMMUNITY_ELECTRIC_COOPERATIVE = "Community Electric Cooperative"
    CRAIG_BOTETOURT_ELECTRIC_COOPERATIVE = "Craig-Botetourt Electric Cooperative"
    DANVILLE_UTILITIES = "Danville Utilities"
    DOMINION_VIRGINIA_POWER = "Dominion Virginia Power"
    MECKLENBURG_ELECTRIC_COOPERATIVE = "Mecklenburg Electric Cooperative"
    NORTHERN_NECK_ELECTRIC_COOPERATIVE = "Northern Neck Electric Cooperative"
    NORTHERN_VIRGINIA_ELECTRIC_COOPERATIVE = "Northern Virginia Electric Cooperative"
    OLD_DOMINION_ELECTRIC_COOPERATIVE = "Old Dominion Electric Cooperative"
    PRINCE_GEORGE_ELECTRIC_COOPERATIVE = "Prince George Electric Cooperative"
    RAPPAHANNOCK_ELECTRIC_COOPERATIVE = "Rapahannock Electric Cooperative"
    SHENANDOAH_VALLEY_ELECTRIC_COOPERATIVE = "Shenandoah Valley Electric Cooperative"
    SOUTHSIDE_ELECTRIC_COOPERATIVE = "Southside Electric Cooperative"
    AVISTA_UTILITIES = "Avista Utilities"
    BENTON_COUNTY_PUBLIC_UTILITY_DISTRICT = "Benton County Public Utility District"
    BIG_BEND_ELECTRIC = "Big Bend Electric"
    CHELAN_COUNTY_PUBLIC_UTILITY_DISTRICT = "Chelan County Public Utility District"
    CITY_OF_MILTON = "City of Milton"
    CLARK_PUBLIC_UTILITIES = "Clark Public Utilities"
    COLUMBIA_RURAL_ELECTRIC = "Columbia Rural Electric"
    DOUGLAS_COUNTY_PUBLIC_UTILITY_DISTRICT = "Douglas County Public Utility District"
    ELMURST_MUTUAL = "Elmurst Mutual"
    FRANKLIN_COUNTY_PUBLIC_UTILITY_DISTRICT = "Franklin County Public Utility District"
    GRANT_COUNTY_PUBLIC_UTILITY_DISTRICT = "Grant County Public Utility District"
    KLICKITAT_PUBLIC_UTILITY_DISTRICT = "Klickitat Public Utility District"
    LAKEVIEW_LIGHT_AND_POWER = "Lakeview Light & Power"
    MASON_COUNTY_PUBLIC_UTILITY_DISTRICT_3 = "Mason County Public Utility District 3"
    MODERN_ELECTRIC_WATER = "Modern Electric Water"
    NESPELEM_VALLEY_ELECTRIC = "Nespelem Valley Electric"
    OHOP_MUTUAL = "Ohop Mutual"
    OKANOGAN_COUNTRY_ELECTRIC_AND_PROPANE = "Okanaogan Country Electric & Propane"
    ORCAS_POWER_AND_LIGHT_COOP = "Orcas Power and Light Coop (OPALCO)"
    PARKLAND_LIGHT_AND_WATER = "Parkland Light & Water"
    PENINSULA_LIGHT_CO = "Peninsula Light Co"
    PEND_OREILLE_COUNTY_PUBLIC_UTILITY_DISTRICT = "Pend Oreille County Public Utility District"
    PUGET_SOUND_ENERGY = "Puget Sound Energy"
    SEATTLE_CITY_LIGHT = "Seattle City Light"
    SNOHOMISH_COUNTY_PUBLIC_UTILITY_DISTRICT = "Snohomish County Public Utility District"
    TACOMA_POWER = "Tacoma Power"
    TANNER_ELECTRIC_COOP = "Tanner Electric Coop"
    TOWN_OF_STEILACOOM = "Town of Steilacoom"
    TOWN_OF_EATONVILLE = "Town of Eatonville"
    AMERICAN_ELECTRIC_POWER_APPALACHIAN_POWER_WHEELING_ELECTRIC_POWER = "American Electric Power (Appalachian Power, Wheeling Electric Power)"
    FIRSTENERGY_MON_POWER_POTOMAC_EDISON = "FirstEnergy (Mon Power, Potomac Edison)"
    BLACK_DIAMOND_POWER_COMPANY = "Black Diamond Power Company"
    DAIRYLAND_POWER_COOPERATIVE = "Dairyland Power Cooperative (and its 25 member cooperatives)"
    MADISON_GAS_AND_ELECTRIC = "Madison Gas and Electric"
    WISCONSIN_POWER_AND_LIGHT_COMPANY = "Wisconsin Power and Light Company, a part of Alliant Energy"
    WISCONSIN_PUBLIC_SERVICE_CORPORATION = "Wisconsin Public Service Corporation"
    CHEYENNE_LIGHT_FUEL_AND_POWER = "Cheyenne Light, Fuel & Power"
    LOWER_VALLEY_ENERGY = "Lower Valley Energy"
    BRIDGER_VALLEY = "Bridger Valley"
    NIOBRARA_ELECTRIC = "Niobrara Electric"
    BLACK_HILLS_POWER = "Black Hills Power"
    POWDER_RIVER_ENERGY_CORPORATION = "Powder River Energy Corporation (A cooperative of Touchstone Energy)"
    CARBON_POWER_AND_LIGHT = "Carbon Power & Light (A cooperative of Touchstone Energy)"
    PACIFICORP_ROCKY_MOUNTAIN_POWER_2 = "PacifiCorp (Rocky Mountain Power)"
    
class State(StrEnum):
    AL = "Alabama"
    AK = "Alaska"
    AZ = "Arizona"
    AR = "Arkansas"
    CA = "California"
    CO = "Colorado"
    CT = "Connecticut"
    DE = "Delaware"
    FL = "Florida"
    GA = "Georgia"
    HI = "Hawaii"
    ID = "Idaho"
    IL = "Illinois"
    IN = "Indiana"
    IA = "Iowa"
    KS = "Kansas"
    KY = "Kentucky"
    LA = "Louisiana"
    ME = "Maine"
    MD = "Maryland"
    MA = "Massachusetts"
    MI = "Michigan"
    MN = "Minnesota"
    MS = "Mississippi"
    MO = "Missouri"
    MT = "Montana"
    NE = "Nebraska"
    NV = "Nevada"
    NH = "New Hampshire"
    NJ = "New Jersey"
    NM = "New Mexico"
    NY = "New York"
    NC = "North Carolina"
    ND = "North Dakota"
    OH = "Ohio"
    OK = "Oklahoma"
    OR = "Oregon"
    PA = "Pennsylvania"
    RI = "Rhode Island"
    SC = "South Carolina"
    SD = "South Dakota"
    TN = "Tennessee"
    TX = "Texas"
    UT = "Utah"
    VT = "Vermont"
    VA = "Virginia"
    WA = "Washington"
    WV = "West Virginia"
    WI = "Wisconsin"
    WY = "Wyoming"

class UtilityCommission(Enum):
    FERC = "Federal Energy Regulatory Commission"
    ALABAMA = "Alabama Public Service Commission"
    ALASKA = "Alaska Regulatory Commission"
    ARIZONA = "Arizona Corporation Commission"
    ARKANSAS = "Arkansas Public Service Commission"
    CALIFORNIA = "California Public Utilities Commission"
    COLORADO = "Colorado Public Utilities Commission"
    CONNECTICUT = "Connecticut Public Utilities Regulatory Authority"
    DELAWARE = "Delaware Public Service Commission"
    FLORIDA = "Florida Public Service Commission"
    GEORGIA = "Georgia Public Service Commission"
    HAWAII = "Hawaii Public Utilities Commission"
    IDAHO = "Idaho Public Utilities Commission"
    ILLINOIS = "Illinois Commerce Commission"
    INDIANA = "Indiana Utility Regulatory Commission"
    IOWA = "Iowa Utilities Board"
    KANSAS = "Kansas Corporation Commission"
    KENTUCKY = "Kentucky Public Service Commission"
    LOUISIANA = "Louisiana Public Service Commission"
    MAINE = "Maine Public Utilities Commission"
    MARYLAND = "Maryland Public Service Commission"
    MASSACHUSETTS = "Massachusetts Department of Public Utilities"
    MICHIGAN = "Michigan Public Service Commission"
    MINNESOTA = "Minnesota Public Utilities Commission"
    MISSISSIPPI = "Mississippi Public Service Commission"
    MISSOURI = "Missouri Public Service Commission"
    MONTANA = "Montana Public Service Commission"
    NEBRASKA = "Nebraska Public Service Commission"
    NEVADA = "Nevada Public Utilities Commission"
    NEW_HAMPSHIRE = "New Hampshire Public Utilities Commission"
    NEW_JERSEY = "New Jersey Board of Public Utilities"
    NEW_MEXICO = "New Mexico Public Regulation Commission"
    NEW_YORK = "New York Public Service Commission"
    NORTH_CAROLINA = "North Carolina Utilities Commission"
    NORTH_DAKOTA = "North Dakota Public Service Commission"
    OHIO = "Ohio Public Utilities Commission"
    OKLAHOMA = "Oklahoma Corporation Commission"
    OREGON = "Oregon Public Utility Commission"
    PENNSYLVANIA = "Pennsylvania Public Utility Commission"
    RHODE_ISLAND = "Rhode Island Public Utilities Commission"
    SOUTH_CAROLINA = "South Carolina Public Service Commission"
    SOUTH_DAKOTA = "South Dakota Public Utilities Commission"
    TENNESSEE = "Tennessee Public Utility Commission"
    TEXAS = "Texas Public Utility Commission"
    UTAH = "Utah Public Service Commission"
    VERMONT = "Vermont Public Utility Commission"
    VIRGINIA = "Virginia State Corporation Commission"
    WASHINGTON_DC = "Washington, D.C. Public Service Commission"
    WEST_VIRGINIA = "West Virginia Public Service Commission"
    WISCONSIN = "Wisconsin Public Service Commission"
    WYOMING = "Wyoming Public Service Commission"