""" This module contains tests for all examples."""

import pytest

from gdm import (
    DistributionBus,
    VoltageSourceEquipment,
    DistributionVoltageSource,
    ConcentricCableEquipment,
    BareConductorEquipment,
    SequenceImpedanceBranchEquipment,
    MatrixImpedanceBranchEquipment,
    GeometryBranchEquipment,
    MatrixImpedanceBranch,
    SequenceImpedanceBranch,
    GeometryBranch,
    PhaseCapacitorEquipment,
    CapacitorEquipment,
    DistributionCapacitor,
    DistributionLoad,
    WindingEquipment,
    DistributionTransformer,
    DistributionTransformerEquipment,
    DistributionFeeder,
    DistributionSubstation,
    SolarEquipment,
    DistributionSolar,
    DistributionRegulator,
    VoltageCapacitorController,
    ActivePowerCapacitorController,
    ReactivePowerCapacitorController,
    CurrentCapacitorController,
    DailyTimedCapacitorController,
    PowerfactorInverterController,
    VoltVarInverterController,
    VoltVarVoltWattInverterController,
    RegulatorController,
    MatrixImpedanceFuseEquipment,
    MatrixImpedanceFuse,
    MatrixImpedanceSwitch,
    Curve,
    TimeCurrentCurve,
    MatrixImpedanceRecloserEquipment,
    MatrixImpedanceRecloser,
    RecloserControllerEquipment,
    DistributionSwitchController,
    DistributionRecloserController,
    MatrixImpedanceSwitchEquipment,
    VoltWattInverterController,
    InverterEquipment,
)

DIST_INTERFACES = [
    DistributionBus,
    VoltageSourceEquipment,
    DistributionVoltageSource,
    ConcentricCableEquipment,
    BareConductorEquipment,
    SequenceImpedanceBranchEquipment,
    MatrixImpedanceBranchEquipment,
    GeometryBranchEquipment,
    MatrixImpedanceBranch,
    SequenceImpedanceBranch,
    GeometryBranch,
    PhaseCapacitorEquipment,
    CapacitorEquipment,
    DistributionCapacitor,
    DistributionLoad,
    WindingEquipment,
    DistributionTransformer,
    DistributionTransformerEquipment,
    DistributionFeeder,
    DistributionSubstation,
    SolarEquipment,
    DistributionSolar,
    DistributionRegulator,
    DistributionSolar,
    DistributionRegulator,
    VoltageCapacitorController,
    ActivePowerCapacitorController,
    ReactivePowerCapacitorController,
    CurrentCapacitorController,
    DailyTimedCapacitorController,
    Curve,
    PowerfactorInverterController,
    VoltVarInverterController,
    VoltVarVoltWattInverterController,
    RegulatorController,
    MatrixImpedanceFuseEquipment,
    MatrixImpedanceFuse,
    MatrixImpedanceSwitch,
    TimeCurrentCurve,
    MatrixImpedanceRecloserEquipment,
    MatrixImpedanceRecloser,
    RecloserControllerEquipment,
    DistributionSwitchController,
    DistributionRecloserController,
    MatrixImpedanceSwitchEquipment,
    VoltWattInverterController,
    InverterEquipment,
]


@pytest.mark.parametrize("dist_interface", DIST_INTERFACES)
def test_eval(dist_interface):
    assert dist_interface.example()
