"""This module contains tests for all examples."""

import pytest

from gdm.distribution.components import (
    DistributionVoltageSource,
    SequenceImpedanceBranch,
    MatrixImpedanceRecloser,
    DistributionTransformer,
    DistributionSubstation,
    MatrixImpedanceBranch,
    DistributionRegulator,
    MatrixImpedanceSwitch,
    DistributionCapacitor,
    MatrixImpedanceFuse,
    DistributionBattery,
    DistributionFeeder,
    DistributionSolar,
    DistributionLoad,
    DistributionBus,
    GeometryBranch,
)

from gdm.distribution.equipment import (
    DistributionTransformerEquipment,
    MatrixImpedanceRecloserEquipment,
    SequenceImpedanceBranchEquipment,
    MatrixImpedanceBranchEquipment,
    MatrixImpedanceSwitchEquipment,
    MatrixImpedanceFuseEquipment,
    RecloserControllerEquipment,
    ConcentricCableEquipment,
    GeometryBranchEquipment,
    PhaseCapacitorEquipment,
    VoltageSourceEquipment,
    BareConductorEquipment,
    CapacitorEquipment,
    InverterEquipment,
    WindingEquipment,
    BatteryEquipment,
    SolarEquipment,
)

from gdm.distribution.controllers import (
    PeakShavingBaseLoadingControlSetting,
    ReactivePowerCapacitorController,
    ActivePowerCapacitorController,
    DistributionRecloserController,
    CapacityFirmingControlSetting,
    SelfConsumptionControlSetting,
    DailyTimedCapacitorController,
    DistributionSwitchController,
    VoltageCapacitorController,
    CurrentCapacitorController,
    DemandChargeControlSetting,
    PowerfactorControlSetting,
    TimeBasedControlSetting,
    TimeOfUseControlSetting,
    VoltWattControlSetting,
    VoltVarControlSetting,
    RegulatorController,
)

from gdm.distribution.common import (
    TimeCurrentCurve,
    VoltageLimitSet,
    ThermalLimitSet,
    Curve,
)

from gdm.distribution.market import (
    DistributionTariff,
    SeasonalTOURates,
    TOURatePeriod,
    DemandCharge,
    FixedCharge,
    TieredRate,
)

DIST_INTERFACES = [
    DistributionVoltageSource,
    SequenceImpedanceBranch,
    MatrixImpedanceRecloser,
    DistributionTransformer,
    DistributionSubstation,
    MatrixImpedanceBranch,
    DistributionRegulator,
    MatrixImpedanceSwitch,
    DistributionCapacitor,
    MatrixImpedanceFuse,
    DistributionBattery,
    DistributionFeeder,
    DistributionSolar,
    DistributionLoad,
    DistributionBus,
    GeometryBranch,
    DistributionTransformerEquipment,
    MatrixImpedanceRecloserEquipment,
    SequenceImpedanceBranchEquipment,
    MatrixImpedanceBranchEquipment,
    MatrixImpedanceSwitchEquipment,
    MatrixImpedanceFuseEquipment,
    RecloserControllerEquipment,
    ConcentricCableEquipment,
    GeometryBranchEquipment,
    PhaseCapacitorEquipment,
    VoltageSourceEquipment,
    BareConductorEquipment,
    CapacitorEquipment,
    InverterEquipment,
    WindingEquipment,
    BatteryEquipment,
    SolarEquipment,
    PeakShavingBaseLoadingControlSetting,
    ReactivePowerCapacitorController,
    ActivePowerCapacitorController,
    DistributionRecloserController,
    CapacityFirmingControlSetting,
    SelfConsumptionControlSetting,
    DailyTimedCapacitorController,
    DistributionSwitchController,
    VoltageCapacitorController,
    CurrentCapacitorController,
    DemandChargeControlSetting,
    PowerfactorControlSetting,
    TimeBasedControlSetting,
    TimeOfUseControlSetting,
    VoltWattControlSetting,
    VoltVarControlSetting,
    RegulatorController,
    TimeCurrentCurve,
    VoltageLimitSet,
    ThermalLimitSet,
    Curve,
    DistributionTariff,
    SeasonalTOURates,
    TOURatePeriod,
    DemandCharge,
    FixedCharge,
    TieredRate,
]


@pytest.mark.parametrize("dist_interface", DIST_INTERFACES)
def test_eval(dist_interface):
    assert dist_interface.example()
