import pytest

from gdm.distribution.components import (
    DistributionVoltageSource,
    SequenceImpedanceBranch,
    MatrixImpedanceRecloser,
    DistributionTransformer,
    DistributionSubstation,
    MatrixImpedanceBranch,
    DistributionRegulator,
    MatrixImpedanceSwitch,
    DistributionCapacitor,
    MatrixImpedanceFuse,
    DistributionBattery,
    DistributionFeeder,
    DistributionSolar,
    DistributionLoad,
    DistributionBus,
    GeometryBranch,
)

from gdm.distribution.equipment import (
    DistributionTransformerEquipment,
    MatrixImpedanceRecloserEquipment,
    SequenceImpedanceBranchEquipment,
    MatrixImpedanceBranchEquipment,
    MatrixImpedanceSwitchEquipment,
    MatrixImpedanceFuseEquipment,
    RecloserControllerEquipment,
    ConcentricCableEquipment,
    GeometryBranchEquipment,
    PhaseCapacitorEquipment,
    VoltageSourceEquipment,
    BareConductorEquipment,
    CapacitorEquipment,
    InverterEquipment,
    WindingEquipment,
    BatteryEquipment,
    SolarEquipment,
)

from gdm.distribution.controllers import (
    PeakShavingBaseLoadingControlSetting,
    ReactivePowerCapacitorController,
    ActivePowerCapacitorController,
    DistributionRecloserController,
    CapacityFirmingControlSetting,
    SelfConsumptionControlSetting,
    DailyTimedCapacitorController,
    DistributionSwitchController,
    VoltageCapacitorController,
    CurrentCapacitorController,
    DemandChargeControlSetting,
    PowerfactorControlSetting,
    TimeBasedControlSetting,
    TimeOfUseControlSetting,
    VoltWattControlSetting,
    VoltVarControlSetting,
    RegulatorController,
)

from gdm.distribution import (
    TimeCurrentCurve,
    Curve,
)


CLASSES_TO_CHECK_JSON_SCHEMA = [
    DistributionVoltageSource,
    SequenceImpedanceBranch,
    MatrixImpedanceRecloser,
    DistributionTransformer,
    DistributionSubstation,
    MatrixImpedanceBranch,
    DistributionRegulator,
    MatrixImpedanceSwitch,
    DistributionCapacitor,
    MatrixImpedanceFuse,
    DistributionBattery,
    DistributionFeeder,
    DistributionSolar,
    DistributionLoad,
    DistributionBus,
    GeometryBranch,
    DistributionTransformerEquipment,
    MatrixImpedanceRecloserEquipment,
    SequenceImpedanceBranchEquipment,
    MatrixImpedanceBranchEquipment,
    MatrixImpedanceSwitchEquipment,
    MatrixImpedanceFuseEquipment,
    RecloserControllerEquipment,
    ConcentricCableEquipment,
    GeometryBranchEquipment,
    PhaseCapacitorEquipment,
    VoltageSourceEquipment,
    BareConductorEquipment,
    CapacitorEquipment,
    InverterEquipment,
    WindingEquipment,
    BatteryEquipment,
    SolarEquipment,
    PeakShavingBaseLoadingControlSetting,
    ReactivePowerCapacitorController,
    ActivePowerCapacitorController,
    DistributionRecloserController,
    CapacityFirmingControlSetting,
    SelfConsumptionControlSetting,
    DailyTimedCapacitorController,
    DistributionSwitchController,
    VoltageCapacitorController,
    CurrentCapacitorController,
    DemandChargeControlSetting,
    PowerfactorControlSetting,
    TimeBasedControlSetting,
    TimeOfUseControlSetting,
    VoltWattControlSetting,
    VoltVarControlSetting,
    RegulatorController,
    TimeCurrentCurve,
    Curve,
]


@pytest.mark.parametrize("component", CLASSES_TO_CHECK_JSON_SCHEMA)
def test_json_schema(component):
    json_schema = component.model_json_schema()
    assert isinstance(json_schema, dict)
