import pytest

from gdm import (
    DistributionBus,
    VoltageSourceEquipment,
    DistributionVoltageSource,
    ConcentricCableEquipment,
    BareConductorEquipment,
    SequenceImpedanceBranchEquipment,
    MatrixImpedanceBranchEquipment,
    GeometryBranchEquipment,
    MatrixImpedanceBranch,
    SequenceImpedanceBranch,
    GeometryBranch,
    PhaseCapacitorEquipment,
    CapacitorEquipment,
    DistributionCapacitor,
    DistributionLoad,
    WindingEquipment,
    DistributionTransformer,
    DistributionTransformerEquipment,
    DistributionFeeder,
    DistributionSubstation,
    SolarEquipment,
    DistributionSolar,
    DistributionRegulator,
    VoltageCapacitorController,
    ActivePowerCapacitorController,
    ReactivePowerCapacitorController,
    CurrentCapacitorController,
    DailyTimedCapacitorController,
    PowerfactorInverterController,
    VoltVarInverterController,
    VoltVarVoltWattInverterController,
    RegulatorController,
    MatrixImpedanceFuseEquipment,
    MatrixImpedanceFuse,
    MatrixImpedanceSwitch,
    Curve,
    TimeCurrentCurve,
    MatrixImpedanceRecloserEquipment,
    MatrixImpedanceRecloser,
    RecloserControllerEquipment,
    DistributionSwitchController,
    DistributionRecloserController,
    MatrixImpedanceSwitchEquipment,
    VoltWattInverterController,
    InverterEquipment,
)


CLASSES_TO_CHECK_JSON_SCHEMA = [
    DistributionBus,
    VoltageSourceEquipment,
    DistributionVoltageSource,
    ConcentricCableEquipment,
    BareConductorEquipment,
    SequenceImpedanceBranchEquipment,
    MatrixImpedanceBranchEquipment,
    GeometryBranchEquipment,
    MatrixImpedanceBranch,
    SequenceImpedanceBranch,
    GeometryBranch,
    PhaseCapacitorEquipment,
    CapacitorEquipment,
    DistributionCapacitor,
    DistributionLoad,
    WindingEquipment,
    DistributionTransformer,
    DistributionTransformerEquipment,
    DistributionFeeder,
    DistributionSubstation,
    SolarEquipment,
    DistributionSolar,
    DistributionRegulator,
    VoltageCapacitorController,
    ActivePowerCapacitorController,
    ReactivePowerCapacitorController,
    CurrentCapacitorController,
    DailyTimedCapacitorController,
    PowerfactorInverterController,
    VoltVarInverterController,
    VoltVarVoltWattInverterController,
    RegulatorController,
    MatrixImpedanceFuseEquipment,
    MatrixImpedanceFuse,
    MatrixImpedanceSwitch,
    Curve,
    TimeCurrentCurve,
    MatrixImpedanceRecloserEquipment,
    MatrixImpedanceRecloser,
    RecloserControllerEquipment,
    DistributionSwitchController,
    DistributionRecloserController,
    MatrixImpedanceSwitchEquipment,
    VoltWattInverterController,
    InverterEquipment,
]


@pytest.mark.parametrize("component", CLASSES_TO_CHECK_JSON_SCHEMA)
def test_json_schema(component):
    json_schema = component.model_json_schema()
    assert isinstance(json_schema, dict)
