""" This module contains tests for all examples."""

import pytest

from gdm import (
    DistributionBus,
    DistributionComponent,
    PhaseVoltageSourceEquipment,
    VoltageSourceEquipment,
    DistributionVoltageSource,
    ConcentricCableEquipment,
    BareConductorEquipment,
    SequenceImpedanceBranchEquipment,
    MatrixImpedanceBranchEquipment,
    GeometryBranchEquipment,
    DistributionBranch,
    MatrixImpedanceBranch,
    SequenceImpedanceBranch,
    GeometryBranch,
    PhaseCapacitorEquipment,
    CapacitorEquipment,
    DistributionCapacitor,
    DistributionLoad,
    WindingEquipment,
    TapWindingEquipment,
    DistributionTransformer,
    DistributionTransformerEquipment,
    DistributionFeeder,
    DistributionSubstation,
    SolarEquipment,
    DistributionSolar,
    DistributionRegulator,
    CapacitorController,
    VoltageCapacitorController,
    ActivePowerCapacitorController,
    ReactivePowerCapacitorController,
    CurrentCapacitorController,
    DailyTimedCapacitorController,
    Curve,
    InverterController,
    PowerfactorInverterController,
    VoltVarInverterController,
    VoltVarVoltWattInverterController,
    RegulatorController,
    DistributionSwitch,
    DistributionFuse,
    SwitchedDistributionBranch,
    MatrixImpedanceFuseEquipment,
    MatrixImpedanceFuse,
    MatrixImpedanceSwitch,
)

DIST_INTERFACES = [
    DistributionBus,
    DistributionComponent,
    PhaseVoltageSourceEquipment,
    VoltageSourceEquipment,
    DistributionVoltageSource,
    ConcentricCableEquipment,
    BareConductorEquipment,
    SequenceImpedanceBranchEquipment,
    MatrixImpedanceBranchEquipment,
    GeometryBranchEquipment,
    DistributionBranch,
    MatrixImpedanceBranch,
    SequenceImpedanceBranch,
    GeometryBranch,
    PhaseCapacitorEquipment,
    CapacitorEquipment,
    DistributionCapacitor,
    DistributionLoad,
    WindingEquipment,
    TapWindingEquipment,
    DistributionTransformer,
    DistributionTransformerEquipment,
    DistributionFeeder,
    DistributionSubstation,
    SolarEquipment,
    DistributionSolar,
    DistributionRegulator,
    DistributionSolar,
    DistributionRegulator,
    CapacitorController,
    VoltageCapacitorController,
    ActivePowerCapacitorController,
    ReactivePowerCapacitorController,
    CurrentCapacitorController,
    DailyTimedCapacitorController,
    Curve,
    InverterController,
    PowerfactorInverterController,
    VoltVarInverterController,
    VoltVarVoltWattInverterController,
    RegulatorController,
    DistributionSwitch,
    DistributionFuse,
    SwitchedDistributionBranch,
    MatrixImpedanceFuseEquipment,
    MatrixImpedanceFuse,
    MatrixImpedanceSwitch,
]


@pytest.mark.parametrize("dist_interface", DIST_INTERFACES)
def test_eval(dist_interface):
    assert dist_interface.example()
